"use strict";
// Standalone app: changing assumptions recalculates rules; row edits become explicit persistent overrides.
function rangePicker(startIn,endIn){
  var box = el("div","rp"), sum = el("div","rp-sum"), head = el("div","rp-head"), grid = el("div","rp-grid"), hint = el("p","rp-hint"), cal = el("div","rp-cal"), foot = el("div","rp-foot"), ok = el("button","btn","OK");
  var sD = el("button"), eD = el("button"); sD.type = eD.type = "button"; sD.appendChild(el("span",null,"Departure")); eD.appendChild(el("span",null,"Return")); var sB = el("b"), eB = el("b"); sD.appendChild(sB); eD.appendChild(eB); sum.appendChild(sD); sum.appendChild(eD);
  var prev = el("button",null,"‹"), next = el("button",null,"›"), title = el("b"); prev.type = next.type = "button"; prev.setAttribute("aria-label","Previous month"); next.setAttribute("aria-label","Next month");
  head.appendChild(prev); head.appendChild(title); head.appendChild(next);
  ok.type = "button"; foot.appendChild(hint); foot.appendChild(ok); cal.appendChild(head); cal.appendChild(grid); cal.appendChild(foot);
  box.appendChild(sum); box.appendChild(cal); var open = false;
  function setOpen(v){ open = v; cal.hidden = !v; box.classList.toggle("open",v); sD.setAttribute("aria-expanded",String(v)); eD.setAttribute("aria-expanded",String(v)); sync(); }
  var mode = ""; sD.addEventListener("click",function(){ mode = "s"; setOpen(true); }); eD.addEventListener("click",function(){ mode = S ? "e" : "s"; setOpen(true); }); ok.addEventListener("click",function(){ setOpen(false); });
  box.openCal = function(){ setOpen(true); };box.restoreDates=function(s,e){S=s || "";E=e || "";var d=pd(S) || new Date();view=new Date(d.getFullYear(),d.getMonth(),1);draw();setOpen(false);};
  var MON = ["January","February","March","April","May","June","July","August","September","October","November","December"];
  function iso(d){ return d.getFullYear() + "-" + String(d.getMonth()+1).padStart(2,"0") + "-" + String(d.getDate()).padStart(2,"0"); }
  var S = startIn.value || "", E = endIn.value || "", base = pd(S) || new Date(), view = new Date(base.getFullYear(), base.getMonth(), 1), todayIso = iso(new Date());
  function label(v){ var d = pd(v); return d ? d.toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"}) : "Select date"; }
  function sync(){ startIn.value = S; endIn.value = E; sB.textContent = label(S); eB.textContent = label(E); var act = mode || (!S ? "s" : (!E ? "e" : "")); sD.className = open && act === "s" ? "on" : ""; eD.className = open && act === "e" ? "on" : "";
    if (act === "s") hint.textContent = "Tap your departure date.";
    else if (act === "e") hint.textContent = "Tap your return date (or the same day for a day trip).";
    else { var n = Math.round((pd(E) - pd(S)) / 86400000) + 1; hint.textContent = n + (n === 1 ? " day" : " days") + " · " + (n - 1) + (n === 2 ? " night" : " nights") + ". Tap a date box to change it, or tap departure on the calendar to start over."; } }
  function pick(v){
    var m = mode; mode = "";
    if (m === "s"){ S = v; if (E && E < v) E = ""; }
    else if (m === "e" && S){ if (v < S){ S = v; E = ""; } else E = v; }
    else if (S && E){ if (v === S){ S = ""; E = ""; } else if (v === E){ E = ""; } else if (v < S){ S = v; } else { E = v; } }
    else if (!S) S = v;
    else if (v < S) S = v;
    else E = v;
    if (S && E && (pd(E) - pd(S)) / 86400000 + 1 > 60){ E = ""; hint.textContent = "Trips can be up to 60 days."; draw(); startIn.value = S; endIn.value = E;box.dispatchEvent(new Event("packingchange",{bubbles:true}));return; }
    draw();box.dispatchEvent(new Event("packingchange",{bubbles:true}));
  }
  function draw(){
    title.textContent = MON[view.getMonth()] + " " + view.getFullYear(); grid.textContent = "";
    ["S","M","T","W","T","F","S"].forEach(function(d){ grid.appendChild(el("div","dow",d)); });
    var first = view.getDay(), days = new Date(view.getFullYear(), view.getMonth()+1, 0).getDate();
    for (var i = 0; i < first; i++) grid.appendChild(el("div"));
    for (var d = 1; d <= days; d++){ (function(v){ var b = el("button",null,String(+v.slice(8))); b.type = "button"; b.setAttribute("aria-label",label(v));
      var cls = []; if (v === S) cls.push("s"); if (v === E || (v === S && !E)) cls.push("e"); if (S && E && v > S && v < E) cls.push("in"); if (v === todayIso){ cls.push("today"); b.setAttribute("aria-current","date"); } b.className = cls.join(" ");
      if (v === S || v === E) b.setAttribute("aria-pressed","true");
      b.addEventListener("click",function(){ pick(v); }); grid.appendChild(b); })(iso(new Date(view.getFullYear(), view.getMonth(), d))); }
    sync();
  }
  prev.addEventListener("click",function(){ view = new Date(view.getFullYear(), view.getMonth()-1, 1); draw(); });
  next.addEventListener("click",function(){ view = new Date(view.getFullYear(), view.getMonth()+1, 1); draw(); });
  draw(); setOpen(false); return box;
}
function refineSetup(t){
  var testSetup=!!(t && PACK_TEST_MODE && t.id==="PACKING-TEST" && lsGet("test-initial-setup",false));if(t && !testSetup && !t.packingDeleted)return refineTripDetails(t);
  var existing = !!t, old = t, saved = existing ? refineLoad(t) : null, inputs = saved ? saved.inputs : {}, f = el("form","panel form gen-form rs-form"), attemptedId=null,activeStyle=null;
  if(PACK_TEST_MODE)f.appendChild(packingTestBanner());
  f.appendChild(el("h2","k",testSetup ? "Test initial setup":existing ? "Trip basics":"New trip"));
  var styleSelect;if(!existing){styleSelect=sel("rs-style",[["","Usual defaults"]].concat(packingTripStyles().map(function(x){return [x.id,x.name];})),"");f.appendChild(fieldEl("Trip style (optional)",styleSelect));}
  var styleNote=el("p","gen-note");styleNote.hidden=true;f.appendChild(styleNote);
  var where = el("textarea","grow"); where.id = "rs-where"; where.rows = 1; where.placeholder = "City, state or country"; where.value = t ? (t.where || "") : ""; where.setAttribute("autocomplete","off"); where.addEventListener("keydown",function(e){ if (e.key === "Enter"){ e.preventDefault(); } }); function growWhere(){ where.value = where.value.replace(/\n/g," "); where.style.height = "auto"; where.style.height = where.scrollHeight + 2 + "px"; } where.addEventListener("input",growWhere); requestAnimationFrame(growWhere); var start = inp("rs-start","hidden",t ? t.start : ""), end = inp("rs-end","hidden",t ? t.end : ""); where.required = true;
  function reqMark(l){ var a = el("span","req","*"); a.setAttribute("aria-hidden","true"); l.appendChild(a); l.appendChild(el("span","sr-only"," (required)")); return l; } var whereField = fieldEl("Destination",where); reqMark(whereField.querySelector("label")); f.appendChild(whereField); var datesField = el("div","field"); datesField.appendChild(reqMark(el("label",null,"Dates"))); var picker = rangePicker(start,end); datesField.appendChild(picker); f.appendChild(datesField);
  var type = inp("rs-type","hidden",inputs.tripType || "leisure");f.appendChild(type);
  var bag = sel("rs-bag",[["carryon","Carry-on"],["checked","Checked bag"]],inputs.bag || "carryon");
  var mode = sel("rs-mode",[["fly","Flying"],["drive","Driving"],["other","Train or other"]],inputs.mode || "fly");
  f.appendChild(fieldEl("Baggage",bag));
  var occasionLabel=el("label","chipchk"),occasion=inp("rs-occasions","checkbox",null);occasion.checked=!!(saved && (saved.refinements.formalDays || saved.refinements.dinners || saved.refinements.workDays>0 || saved.refinements.work!=="none"));occasionLabel.appendChild(occasion);occasionLabel.appendChild(el("span",null,"Work Tops, Suits, or Nice Dinners?"));f.appendChild(occasionLabel);
  var counts=el("section","gen-opt"),countInputs={};counts.appendChild(el("h3",null,"Outfit needs"));counts.appendChild(el("p","gen-note","Enter days that need each outfit; zero means none. Work tops are for video calls; suit days need full attire."));
  [["workDays","Video-call workdays"],["formalDays","Full suit days"],["dinners","Nice dinners"]].forEach(function(x){var value=saved ? saved.refinements[x[0]]:0;if((x[0]==="formalDays" || x[0]==="workDays") && (value==null || value===""))value=0;var input=inp("rs-"+x[0],"number",value);input.min="0";input.max="60";input.step="1";counts.appendChild(fieldEl(x[1],input));countInputs[x[0]]=input;});
  var equipment=sel("rs-work",[["none","No work equipment"],["laptop","Laptop only"],["work","Full hotel work setup"]],saved ? saved.refinements.work:"none");counts.appendChild(fieldEl("Work equipment",equipment));f.appendChild(counts);
  function countVisibility(){var show=occasion.checked;counts.hidden=!show;Object.keys(countInputs).forEach(function(k){countInputs[k].disabled=!show;countInputs[k].required=show;});equipment.disabled=!show;}
  occasion.addEventListener("change",countVisibility);countVisibility();
  picker.addEventListener("click",function(){try{var max=refineDays(start.value,end.value);Object.keys(countInputs).forEach(function(k){countInputs[k].max=String(max);});}catch(e){}});
  var actField = el("div","field"); actField.appendChild(el("h3","rs-section-title","Activities"));
  var activities = {}, toggles = el("div","refine-toggles"); [["hike","Hiking"],["workout","Workouts"],["water","Swimming"],["fish","Fishing"]].forEach(function(x){ var l = el("label","chipchk"), c = el("input"); c.type = "checkbox"; c.id = "rs-"+x[0]; c.checked = !!(inputs.activities && inputs.activities[x[0]]); l.appendChild(c); l.appendChild(el("span",null,x[1])); toggles.appendChild(l); activities[x[0]] = c; }); actField.appendChild(toggles);
  var rugged=el("input");rugged.type="checkbox";rugged.id="rs-rugged";rugged.checked=!!(saved && saved.refinements.ruggedHike);var ruggedField=el("label","chipchk");ruggedField.appendChild(rugged);ruggedField.appendChild(el("span",null,"Rugged or wet trails"));ruggedField.style.alignSelf="flex-start";actField.appendChild(ruggedField);
  f.insertBefore(actField,occasionLabel);
  function hikingVisibility(){ruggedField.style.display=activities.hike.checked ? "":"none";if(brooksC)brooksC.label.style.display=activities.hike.checked && rugged.checked ? "":"none";}activities.hike.addEventListener("change",hikingVisibility);rugged.addEventListener("change",hikingVisibility);hikingVisibility();
  var opt = el("section","field rs-optional");opt.appendChild(el("h3","rs-section-title","Optional settings"));
  var weather=sel("rs-climate",[["unknown","Not sure yet"],["mild","Mild (60–85°F)"],["cool","Cool (40–60°F)"],["cold","Cold (below 40°F)"],["hot","Hot (above 85°F)"]],saved ? saved.refinements.climate : "unknown");
  var wm = el("div","two rs-optional-fields"); wm.appendChild(fieldEl("Coldest conditions outdoors",weather)); wm.appendChild(fieldEl("Travel mode",mode)); opt.appendChild(wm);
  function chip(id,label,on){ var l = el("label","chipchk"), c = el("input"); c.type = "checkbox"; c.id = id; c.checked = on; l.appendChild(c); l.appendChild(el("span",null,label)); return {label:l,input:c}; }
  var flags = el("div","refine-toggles"), rainC = chip("rs-rain","Rain expected",!!(saved && saved.refinements.rain)), dayC = chip("rs-daypack","Daypack",!!(saved && saved.refinements.daypack)), brooksC = chip("rs-brooks","Also bring Brooks",!!(saved && saved.refinements.brooksToo)), intlC = chip("rs-intl","International",!!inputs.intl);
  [rainC,dayC,brooksC,intlC].forEach(function(c){ flags.appendChild(c.label); }); opt.appendChild(flags); hikingVisibility();
  var rain = rainC.input, daypack = dayC.input, brooks = brooksC.input, intl = intlC.input;
  var exGroup = el("div","rs-group"); exGroup.appendChild(el("p","sub","Trip extras")); var ex = el("div","refine-toggles"), extraChecks={};
  REFINE_EXTRAS.forEach(function(choice){ var c = chip("rs-extra-"+choice.key,choice.label,!!(saved && saved.refinements.extraItems[choice.key])); ex.appendChild(c.label); extraChecks[choice.key]=c.input; }); exGroup.appendChild(ex); opt.appendChild(exGroup);
  f.appendChild(opt);
  if(styleSelect)styleSelect.addEventListener("change",function(){activeStyle=packingTripStyles().find(function(x){return x.id===styleSelect.value;}) || null;var style=activeStyle || {inputs:{tripType:"leisure",bag:"carryon",mode:"fly",activities:{}},refinements:{work:"none",extraItems:{}}};styleNote.hidden=!activeStyle;styleNote.textContent=activeStyle ? "Reusing "+style.name+": "+(style.refinements.packingMode==="extra" ? "Pack extra":"Standard packing")+", "+(style.refinements.laundry && style.refinements.laundry.available ? "laundry after "+style.refinements.laundry.firstWash+" days, then every "+style.refinements.laundry.interval+" days":"no laundry")+". Confirm dates, occasion counts and weather for this trip.":"";type.value=style.inputs.tripType;bag.value=style.inputs.bag;mode.value=style.inputs.mode;equipment.value=style.refinements.work || "none";Object.keys(activities).forEach(function(k){activities[k].checked=!!style.inputs.activities[k];});Object.keys(extraChecks).forEach(function(k){extraChecks[k].checked=!!(style.refinements.extraItems && style.refinements.extraItems[k]);});daypack.checked=!!style.refinements.daypack;rugged.checked=!!style.refinements.ruggedHike;brooks.checked=!!style.refinements.brooksToo;intl.checked=!!style.inputs.intl;weather.value="unknown";rain.checked=false;occasion.checked=!!style.inputs.occasions || equipment.value!=="none";countInputs.workDays.value=0;countInputs.formalDays.value=0;countInputs.dinners.value=0;countVisibility();hikingVisibility();});
  var msg = el("p","gen-error"); msg.setAttribute("role","status"); f.appendChild(msg); var actions = el("div","gen-actions"), go = el("button","btn primary",existing && !t.packingDeleted ? "Update trip & list" : "Generate my list"); go.type = "submit"; actions.appendChild(go); var cancel=generatorLink("Cancel",existing ? "#"+t.id : "#");cancel.addEventListener("click",function(){if(testSetup)lsSet("test-initial-setup",false);});actions.appendChild(cancel); f.appendChild(actions);
  f.addEventListener("submit",function(e){ e.preventDefault(); if (!start.value || !end.value){ msg.textContent = "Pick a departure and return date."; picker.openCal(); return; } var span;try{span=refineDays(start.value,end.value);}catch(err){msg.textContent=err.message;return;}
    var record = Object.assign({},old || {},{name:(function(){ var auto = where.value.trim()+" · "+fmt(start.value); if (!existing) return auto; var oldAuto = (t.where||"")+" · "+(t.start ? fmt(t.start) : ""); return (!t.name || t.name === oldAuto) ? auto : t.name; })(),where:where.value.trim(),start:start.value,end:end.value}); record.id = existing ? t.id : attemptedId || newTripId(record.name,record.where,record.start);attemptedId=record.id;
    if(!counts.hidden && Object.keys(countInputs).some(function(k){var v=+countInputs[k].value;return !Number.isInteger(v) || v<0 || v>span;})){msg.textContent="Outfit counts must be whole numbers from 0 to "+span+".";return;}
    var state = saved ? clone(saved) : refineNewState(record,{tripType:type.value});if(!saved && activeStyle)Object.assign(state.refinements,clone(activeStyle.refinements));var before = refineSnapshot(state); state.inputs = {where:record.where,start:record.start,end:record.end,tripType:type.value,bag:bag.value,mode:mode.value,intl:intl.checked,activities:{}};
    Object.keys(activities).forEach(function(k){ state.inputs.activities[k] = activities[k].checked; });
    Object.keys(extraChecks).forEach(function(key){state.refinements.extraItems[key]=extraChecks[key].checked;});
    state.refinements.daypack=daypack.checked; state.refinements.climate=weather.value; state.refinements.rain=rain.checked; state.refinements.ruggedHike=rugged.checked; state.refinements.brooksToo=brooks.checked;
    state.refinements.work=counts.hidden ? "none":equipment.value;state.refinements.workDays=counts.hidden ? 0:+countInputs.workDays.value;state.refinements.formalDays=counts.hidden ? 0:+countInputs.formalDays.value;state.refinements.dinners=counts.hidden ? 0:+countInputs.dinners.value;
    if(!activeStyle)state.inputs.tripType=state.refinements.work!=="none" || state.refinements.workDays>0 ? (state.refinements.formalDays || state.refinements.dinners ? "mixed":"work") : state.refinements.formalDays ? "event":"leisure";
    if(!counts.hidden){["Work","Events"].forEach(function(focus){state.decisionReviews[focus]=refineDecisionKey(state,focus);});}
    if (!existing){ state.reviewed = {Bag:true,Activities:true}; if (weather.value !== "unknown") state.reviewed.Weather = true; if (Object.keys(extraChecks).some(function(k){ return extraChecks[k].checked; })) state.reviewed.Extras = true; if (type.value === "work") state.reviewed.Work = true; if (type.value === "event") state.reviewed.Events = true; }
    state.refinements.formalDays = Math.min(span,state.refinements.formalDays); state.refinements.dinners=Math.min(span,state.refinements.dinners);if(state.refinements.workDays!=null)state.refinements.workDays=Math.min(span,state.refinements.workDays); if (existing){state.undo = before;delete state.undoProfile;}
    var result = state.legacy ? refineLegacyResult(state) : refineEvaluate(state,generatorPrefs(),null); go.disabled = true;
    var patch = Object.assign({},RAW[record.id] || {},{name:record.name,where:record.where,start:record.start,end:record.end,packingDeleted:false}); if (!existing) Object.assign(patch,{status:"Researching",bookings:{},days:[],createdAt:Date.now()});
    refineSaveTrip(record,patch,state,result).then(function(){ setupDraft.clear();if(GEN_DELETED_LIST && GEN_DELETED_LIST.id===record.id)GEN_DELETED_LIST=null;if(testSetup)lsSet("test-initial-setup",false);RAW[record.id] = patch; rebuild(); location.hash = record.id; }).catch(function(){ go.disabled = false; msg.textContent = "Could not save the trip. Check browser storage and try again."; });
  });var setupDraft=packingDraftAttach(f,"setup:"+(existing ? t.id:"new"),existing ? JSON.stringify([inputs,saved.refinements]):"new-trip-v1",{extras:[start,end],restoreEvents:false,contextLegacyOmit:["rs-brooks"],beforeRestore:function(data){var style=data.fields["rs-style"];if(styleSelect && style){styleSelect.value=style.value;styleSelect.dispatchEvent(new Event("change"));}},onRestore:function(){["workDays","formalDays"].forEach(function(key){if(countInputs[key].value==="")countInputs[key].value="0";});picker.restoreDates(start.value,end.value);countVisibility();hikingVisibility();growWhere();}});return f;
}
function refineTripDetails(t){
  var state=refineLoad(t),n=clone(state),f=el("form","panel form gen-form rs-form"),error=el("p","gen-error");
  f.appendChild(el("h2","k","Trip details"));f.appendChild(el("p","gen-note","Change your destination, dates or travel arrangements. Outfit needs, weather and activities each have their own card in Trip plan."));
  var where=inp("rs-where","text",t.where),start=inp("rs-start","hidden",t.start),end=inp("rs-end","hidden",t.end);where.required=true;f.appendChild(fieldEl("Destination",where));var picker=rangePicker(start,end);f.appendChild(picker);
  var bag=sel("rs-bag",[["carryon","Carry-on"],["checked","Checked bag"]],state.inputs.bag),mode=sel("rs-mode",[["fly","Flying"],["drive","Driving"],["other","Train or other"]],state.inputs.mode),intl=inp("rs-intl","checkbox",null),long=inp("rs-longFlight","checkbox",null);intl.checked=!!state.inputs.intl;long.checked=!!state.refinements.longFlight;
  f.appendChild(fieldEl("Baggage",bag));f.appendChild(fieldEl("Travel mode",mode));f.appendChild(fieldEl("International trip",intl));f.appendChild(fieldEl("Long international flight",long));
  function flightVisibility(){long.parentNode.hidden=!long.checked && (mode.value!=="fly" || !intl.checked);}mode.addEventListener("change",flightVisibility);intl.addEventListener("change",flightVisibility);long.addEventListener("change",flightVisibility);flightVisibility();
  var go=el("button","btn primary","Update trip & recalculate");go.type="submit";f.appendChild(error);f.appendChild(go);f.appendChild(generatorLink("Cancel","#"+t.id));
  var draft=packingDraftAttach(f,"trip-details:"+t.id,JSON.stringify([state.inputs,state.refinements.longFlight]),{extras:[start,end],restoreEvents:false,onRestore:function(){picker.restoreDates(start.value,end.value);flightVisibility();}});
  f.addEventListener("submit",function(event){event.preventDefault();if(!start.value || !end.value){error.textContent="Pick a departure and return date.";picker.openCal();return;}var days;try{days=refineDays(start.value,end.value);}catch(e){error.textContent=e.message;return;}
    if(["workDays","formalDays","dinners"].some(function(key){return n.refinements[key]>days;})){error.textContent="This trip is shorter than your outfit counts. Adjust Outfits & work first, then shorten the dates.";return;}
    n.undo=refineSnapshot(state);delete n.undoProfile;Object.assign(n.inputs,{where:where.value.trim(),start:start.value,end:end.value,bag:bag.value,mode:mode.value,intl:intl.checked});n.refinements.longFlight=long.checked;
    var auto=(t.where || "")+" · "+fmt(t.start),name=!t.name || t.name===auto ? where.value.trim()+" · "+fmt(start.value):t.name,record=Object.assign({},t,{name:name,where:where.value.trim(),start:start.value,end:end.value}),patch=Object.assign({},RAW[t.id],{name:name,where:record.where,start:record.start,end:record.end});
    var result=n.legacy ? refineLegacyResult(n):refineEvaluate(n,generatorPrefs(),[]);go.disabled=true;refineSaveTrip(record,patch,n,result).then(function(){draft.clear();RAW[t.id]=patch;rebuild();location.hash=t.id;}).catch(function(){go.disabled=false;error.textContent="Could not save trip details. Your existing trip is unchanged.";});
  });return f;
}
function refinePage(t){ var w = el("div","stack"), back = el("a","back","← Packing generator"); back.href = "#"; w.appendChild(back); if(PACK_TEST_MODE)w.appendChild(packingTestBanner()); w.appendChild(el("p","muted",[t.where,fmt(t.start)+" – "+fmt(t.end || t.start)].join(" · "))); if(t.packingDeleted){w.appendChild(el("h2",null,"Packing list deleted"));w.appendChild(generatorLink("Generate a packing list","#"+t.id+".edit",true));return w;} var pk = packData(t.id);
  if (!pk.ready){ w.appendChild(el("p",null,"Loading your saved list…")); setTimeout(function(){ if (route().t && route().t.id === t.id) render(); },100); return w; }
  w.appendChild(refineReview(t)); return w;
}
function refineReview(t){
  var state = refineLoad(t), profile = generatorPrefs(), result = state.legacy ? refineLegacyResult(state) : refineEvaluate(state,profile,[]), root = el("div","gen-review"), busy = false, learningNotice=el("div"),exportRevision=0,exportPreparation=Promise.resolve();
  // Standalone app: the last successful export's fingerprint (title + section/item labels) flags later list changes.
  var exportRecordPath="trip/"+t.id+"/pack_meta/export",exportRecord=null,exportFingerprintNow=null,exportChanged=el("p","export-changed","Changed since your last export — export again to update Notes.");exportChanged.id="rr-export-changed";exportChanged.setAttribute("role","status");exportChanged.hidden=true;
  var header = el("section","panel"), exportBox = el("section","panel refine-export"), chips = el("div","refine-chips"), summary = el("div","refine-changes"), warnings = el("div"), list = el("div","gen-review"), error = el("p","gen-error"); error.setAttribute("role","status"); summary.setAttribute("role","status");
  header.appendChild(el("h2","k","Trip plan")); header.appendChild(el("p","muted","Tap a card to change your assumptions. Your list recalculates; manual edits stay.")); header.appendChild(chips);
  var actions=el("div","gen-actions");exportBox.id="rr-export"; actions.appendChild(generatorButton("Packing rules",rules)); actions.appendChild(generatorButton("Packing preferences",generatorPreferences));var deleteButton=generatorButton("Delete list",function(){if(busy)return;busy=true;deleteButton.disabled=true;exportRevision++;blockExport();exportPreparation.catch(function(){}).then(function(){return generatorDeleteList(t);}).then(function(){location.hash="";render();}).catch(function(){busy=false;deleteButton.disabled=false;error.textContent="Could not delete. Storage is full or blocked; try again.";outfitSummary();});});deleteButton.classList.add("packing-danger");actions.appendChild(deleteButton);header.appendChild(actions);var utilities=el("details","gen-opt"),utilityActions=el("div","gen-actions");utilities.appendChild(el("summary",null,"Trip styles & learning"));utilityActions.appendChild(generatorButton("Save trip style",function(){packingTripStyleSheet(state);}));if(!state.legacy && (PACK_TEST_MODE || state.inputs.end<isoToday()))utilityActions.appendChild(generatorButton("Learn from this trip",function(){packingLearningFeedbackSheet(t,state,result);}));utilityActions.appendChild(generatorButton("Packing learning",packingLearningSheet));utilities.appendChild(utilityActions);header.appendChild(utilities);
  root.appendChild(exportChanged); root.appendChild(header); root.appendChild(exportBox); root.appendChild(learningNotice); root.appendChild(error); root.appendChild(summary); root.appendChild(warnings);list.appendChild(el("h2","k","Your packing list")); root.appendChild(list);
  var sectionNodes = {}, sectionSignatures = {};
  function failure(message){error.textContent=message;if(sheetBg){var inline=sheetBg.querySelector('.refine-error');if(!inline){inline=el('p','gen-error refine-error');inline.setAttribute('role','alert');sheetBg.querySelector('.sheet-body').appendChild(inline);}inline.textContent=message;}}
  function commit(next,changed,label,undoProfile){
    if (busy) return Promise.resolve(false); busy = true;blockExport(); error.textContent = ""; next.undo = refineSnapshot(state); delete next.undoProfile;if(undoProfile)next.undoProfile=clone(undoProfile);profile=generatorPrefs();
    var evaluated,applied=false;
    try { evaluated = next.legacy ? refineLegacyResult(next) : refineEvaluate(next,profile,changed); } catch(e){ busy = false; error.textContent = e.message; return Promise.resolve(false); }
    return refinePersist(t,next,evaluated).then(function(){applied=true;var changes = refineChanges(result,evaluated); state = next; result = evaluated; paint(); summary.textContent = ""; summary.appendChild(el("strong",null,label)); var ul = el("ul","gen-summary"); (changes.length ? changes : ["Assumptions updated; your current items already cover this choice."]).slice(0,12).forEach(function(x){ ul.appendChild(el("li",null,x)); }); if (changes.length > 12) ul.appendChild(el("li",null,(changes.length-12)+" more changes shown in the list")); summary.appendChild(ul); summary.appendChild(generatorButton("Undo",undo)); return true; }).catch(function(){ failure("Nothing was applied: browser storage could not save the change."); return false; }).finally(function(){busy=false;if(!applied)outfitSummary();});
  }
  function undo(){ if (!state.undo || busy) return; var previous=clone(state.undo),previousProfile=state.undoProfile,applied=false; delete previous.undo; busy=true;blockExport(); var start=previousProfile ? db.doc("meta/packing").set(previousProfile) : Promise.resolve(); start.then(function(){profile=generatorPrefs();var evaluated=previous.legacy ? refineLegacyResult(previous) : refineEvaluate(previous,profile,null);var headerChanged=["where","start","end"].some(function(key){return previous.inputs[key]!==state.inputs[key];}),patch,record;
      if(headerChanged){var auto=state.inputs.where+" · "+fmt(state.inputs.start),name=t.name===auto ? previous.inputs.where+" · "+fmt(previous.inputs.start):t.name;patch=Object.assign({},RAW[t.id],{name:name,where:previous.inputs.where,start:previous.inputs.start,end:previous.inputs.end});record=Object.assign({},t,patch);}
      return (headerChanged ? refineSaveTrip(record,patch,previous,evaluated):refinePersist(t,previous,evaluated)).then(function(){applied=true;state=previous;result=evaluated;if(headerChanged){RAW[t.id]=patch;rebuild();render();}else{summary.textContent="Last change undone.";paint();}});}).catch(function(){error.textContent="Could not save Undo.";}).finally(function(){busy=false;if(!applied && root.isConnected)outfitSummary();}); }
  function assumptionList(){var r=state.refinements,list=[["Laundry",r.laundry.available ? "planned":"none"],["Packing",r.packingMode],["Extras",REFINE_EXTRAS.filter(function(choice){return r.extraItems[choice.key];}).length+" selected"],["Bag",state.inputs.bag==="carryon" ? "carry-on":"checked"],["Weather",r.climate],["Activities",Object.keys(state.inputs.activities).filter(function(k){return state.inputs.activities[k];}).map(function(k){return {hike:"hiking",workout:"workouts",water:"swimming",fish:"fishing"}[k];}).concat(r.daypack ? ["daypack"] : []).join(", ") || "none"],["Events",r.formalDays+" suit days / "+r.dinners+" dinners"],["Work",r.work+" · "+(r.workDays==null ? "workdays to confirm":r.workDays+" video-call days")],["Flight",r.longFlight ? "long international":"usual"]];
    if(r.dinners>0)list.push(["Dinner outfit",r.dinnerTop && r.dinnerBottoms ? (r.dinnerTop==="other" ? r.dinnerOtherTop:r.dinnerTop==="shortsleeve" ? "short-sleeve shirt":r.dinnerTop==="longsleeve" ? "long-sleeve nice shirt":r.dinnerTop==="buttonup" ? "long-sleeve button-up":r.dinnerTop)+" / "+(r.dinnerBottoms==="other" ? r.dinnerOtherBottoms:r.dinnerBottoms):"choose top and bottoms"]);
    if(r.formalDays>0)list.push(["Suit outfit",r.alternateKhakis ? "suit + khakis":"reusable suit"]);
    if(!state.legacy && refineWardrobe(state).canShare)list.push(["Shirt sharing","check shared days"]);return list;
  }
  function exportFingerprint(data){return JSON.stringify([data.title,data.groups.map(function(g){return [g.title,g.items.map(function(i){return i.label;})];})]);}
  function exportBanner(){exportChanged.hidden=!(exportRecord && exportFingerprintNow!=null && exportRecord.fingerprint!==exportFingerprintNow);}
  function exportRecordSave(fingerprint){if(deleteButton.disabled || (RAW[t.id] && RAW[t.id].packingDeleted))return;var record={fingerprint:fingerprint,at:Date.now()};db.doc(exportRecordPath).set(record).then(function(){exportRecord=record;exportBanner();}).catch(function(){});}
  db.doc(exportRecordPath).get().then(function(snap){exportRecord=snap.exists ? snap.data():null;exportBanner();}).catch(function(){});
  function blockExport(){exportBox.querySelectorAll("#pe-enex,#pe-copy,#pe-md").forEach(function(button){button.disabled=true;});}
  function outfitSummary(){
    var revision=++exportRevision,pending=refinePendingDecisions(state);exportBox.textContent="";exportBox.appendChild(el("h2","k","Export to Notes"));
    var groups=result.groups.map(function(g){return {title:g.title,depart:!!g.depart,items:g.items.map(refineLabel)};});
    var data={title:(t.name || t.where || "Trip")+" — Packing List",detail:[t.where,t.start ? t.start+(t.end && t.end!==t.start ? " – "+t.end:""):""].filter(Boolean).join(" · "),groups:groups.map(function(g){return {title:g.title,items:g.items.map(function(label){return {label:label,checked:false};})};})};
    var fingerprint=exportFingerprint(data);exportFingerprintNow=fingerprint;exportBanner();
    if(pending.length){var outfitOnly=pending.indexOf("Laundry")<0,laundryOnly=pending.length===1 && !outfitOnly;exportBox.appendChild(el("p","gen-note",laundryOnly ? "Confirm your laundry plan before exporting your list. This long trip has no planned laundry, so clothing covers every day.":"Confirm the remaining "+(outfitOnly ? "outfit choices":"choices")+" before exporting your list."));var confirm=generatorButton(outfitOnly ? "Confirm outfit choices":laundryOnly ? "Confirm laundry plan":"Confirm remaining choices",function(){if(!busy)advance({decisionsOnly:true,exportAfter:true,seen:{}});},true);confirm.id="rr-confirm";exportBox.appendChild(confirm);return;}
    var body=el("div","inline-export");body.id="rr-outfitSummary";exportBox.appendChild(body);
    packExportSheet(t,{container:body,data:data,canExport:function(){return !busy && revision===exportRevision && !refinePendingDecisions(state).length;},onExport:function(){exportRecordSave(fingerprint);return state.legacy ? Promise.resolve():packingLearningCapture(t,state,result);},prepare:function(){
      // Serialize adapter saves so an older preparation cannot overwrite the latest list.
      exportPreparation=exportPreparation.catch(function(){}).then(function(){if(revision!==exportRevision || !body.isConnected)return "stale";return generatorSaveDraft(t,groups,{bag:state.inputs.bag});});return exportPreparation;
    }});
  }
  function advance(flow){var pending=refinePendingDecisions(state),next=pending[0];
    if(!next && !flow.decisionsOnly)next=assumptionList().map(function(x){return x[0];}).find(function(k){return !(state.reviewed||{})[k] && !flow.seen[k];});
    if(next){assumptions(next,flow);return;}closeSheet();if(flow.exportAfter)exportBox.scrollIntoView({block:"nearest"});
  }
  function outfitMenu(){var body=openSheet("Outfits & work"),pending=refinePendingDecisions(state);body.appendChild(el("p","gen-note","Set days and equipment, then adjust the outfit choices relevant to this trip. Choices needing confirmation are marked."));
    function choice(label,open,needed){var b=generatorButton(label,open);b.setAttribute("aria-label",label);if(needed){b.setAttribute("aria-description","Needs confirmation");b.appendChild(el("span","trip-plan-confirm","Needs confirmation"));b.classList.add("needs-attention");}body.appendChild(b);}
    choice("Days & work equipment",function(){assumptions("Outfits & work");},pending.indexOf("Work")>=0 || pending.indexOf("Events")>=0);
    assumptionList().filter(function(x){return ["Dinner outfit","Suit outfit","Shirt sharing"].indexOf(x[0])>=0;}).forEach(function(x){choice(x[0]+": "+x[1],function(){assumptions(x[0]);},pending.indexOf(x[0])>=0);});
  }
  // Standalone app: one visible overview replaces the nested Adjust trip menu.
  function tripPlan(pending){
    function count(value,label){return value+" "+label+(value===1 ? "":"s");}
    var r=state.refinements,grid=el("div","trip-plan-grid"),outfitPending=pending.filter(function(x){return x!=="Laundry";});grid.id="rr-adjust";grid.setAttribute("aria-label","Trip plan");
    function card(title,description,open,status,wide){var node=generatorButton("",open);node.className="trip-plan-card"+(wide ? " trip-plan-wide":"")+(status ? " needs-attention":"");node.setAttribute("aria-label",title);node.setAttribute("aria-description",description+". "+(status || "Edit"));node.appendChild(el("strong","trip-plan-title",title));node.appendChild(el("span","trip-plan-summary",description));node.appendChild(el("span","trip-plan-status",status || "Edit →"));grid.appendChild(node);return node;}
    var travel=generatorLink("","#"+t.id+".edit");travel.className="trip-plan-card";travel.setAttribute("aria-label","Trip details: destination, dates & travel");travel.appendChild(el("strong","trip-plan-title","Travel"));travel.appendChild(el("span","trip-plan-summary",(state.inputs.bag==="carryon" ? "Carry-on":"Checked bag")+" · "+({fly:"Flying",drive:"Driving",other:"Train or other"}[state.inputs.mode] || "Travel")+" · "+(state.inputs.intl ? "International":"Domestic")));travel.setAttribute("aria-description",travel.querySelector(".trip-plan-summary").textContent+". Edit dates and travel.");travel.appendChild(el("span","trip-plan-status","Dates & travel →"));travel.addEventListener("click",function(){if(PACK_TEST_MODE)lsSet("test-initial-setup",false);});grid.appendChild(travel);
    var assumptionsByName={};assumptionList().forEach(function(x){assumptionsByName[x[0]]=x[1];});
    card("Activities",assumptionsByName.Activities==="none" ? "No activities selected":assumptionsByName.Activities,function(){assumptions("Activities");});
    card("Outfits & work",(r.workDays==null ? "Video-call days unconfirmed":count(r.workDays,"video-call day"))+" · "+count(r.formalDays || 0,"suit day")+" · "+count(r.dinners || 0,"dinner")+(r.work!=="none" ? " · "+(r.work==="work" ? "Full work setup":"Laptop"):""),outfitMenu,outfitPending.length ? count(outfitPending.length,"outfit choice")+" to confirm":"",true);
    card("Weather",({unknown:"Unconfirmed · provisional layers",mild:"Mild · 60–85°F",cool:"Cool · 40–60°F",cold:"Cold · below 40°F",hot:"Hot · above 85°F"}[r.climate] || r.climate)+(r.rain ? " · Rain":"")+(r.warmWeather ? " · Warmer weather too":""),function(){assumptions("Weather");},r.climate==="unknown" ? "Choose conditions":"");
    card("Laundry",r.laundry.available ? "First wash after "+r.laundry.firstWash+" days; then every "+r.laundry.interval+" days":(refineLongTripNoLaundry(state) ? "No planned laundry · clothing for all "+refineDays(state.inputs.start,state.inputs.end)+" days":"No planned laundry"),function(){assumptions("Laundry");},pending.indexOf("Laundry")>=0 ? "Confirm laundry plan":"");
    card("Packing",r.packingMode==="extra" ? "Extra clothing buffer":"Standard quantities",function(){assumptions("Packing");});
    card("Trip extras",REFINE_EXTRAS.filter(function(x){return r.extraItems[x.key];}).map(function(x){return x.label;}).join(", ") || "No optional extras",function(){assumptions("Extras");});
    chips.appendChild(grid);
  }
  function assumptions(focus,flow){
    if(state.legacy && (!t.start || !t.end)){var missing=openSheet("Trip dates needed");missing.appendChild(el("p",null,"Your saved list can still be exported. Set travel dates before enabling automatic quantity calculations."));missing.appendChild(generatorLink("Set trip dates","#"+t.id+".edit",true));return;}
    if (state.legacy){ var body = openSheet("Start automatic refinement"); body.appendChild(el("p",null,"Your existing items stay pinned. Rules will fill missing items; you can return individual rows to automatic quantities afterward.")); body.appendChild(generatorButton("Enable automatic refinement",function(){ var next = clone(state); next.legacy = false; commit(next,null,"Automatic refinement enabled").then(function(ok){ if (ok) closeSheet(); }); },true)); return; }
    var body = openSheet("Refine " + focus.toLowerCase()), f = el("form","form gen-form"), r = state.refinements, n = clone(state), updates = [];
    function select(key,label,options,value,target){var input=sel("rf-"+key,options,value);f.appendChild(fieldEl(label,input));updates.push(function(){target(input.value);});return input;}
    function number(key,label,value,max,target){var input=inp("rf-"+key,"number",value==null ? 0:value);input.min="0";input.max=String(max);input.required=true;f.appendChild(fieldEl(label,input));updates.push(function(){target(+input.value);});return input;}
    function check(key,label,value,target){var input=inp("rf-"+key,"checkbox",null);input.checked=!!value;f.appendChild(fieldEl(label,input));updates.push(function(){target(input.checked);});return input;}
    var note="";
    if(focus==="Packing"){
      select("packing","Packing mode",[["standard","Standard — daily T-shirts, bottoms every two days"],["extra","Pack extra — one T-shirt, two underwear, two socks and one pair of bottoms"]],r.packingMode,function(v){n.refinements.packingMode=v;});
      note="Recalculates clothing only. Your usual accessories stay included. Laundry adjusts coverage; contacts and medications cover the full trip.";
    }else if(focus==="Extras"){
      REFINE_EXTRAS.forEach(function(choice){check("extra-"+choice.key,choice.label,r.extraItems[choice.key],function(v){n.refinements.extraItems[choice.key]=v;});});
      note="Select extras for this trip. Garmin includes its charger. Turning a choice off removes unedited items; pinned manual items stay. Your snacks, water bottle, battery pack and other usual items remain automatic.";
    }else if(focus==="Bag"){
      select("bag","Baggage constraint",[["carryon","Carry-on + personal bag"],["checked","Checked bag + personal bag"]],state.inputs.bag,function(v){n.inputs.bag=v;});
      note="Flags carry-on space conflicts and updates bag checks. It does not change quantities or move items into Wear to travel.";
    }else if(focus==="Weather"){
      select("climate","Coldest conditions you expect outdoors",[["unknown","Unconfirmed"],["mild","Mild (60–85°F)"],["cool","Cool (40–60°F)"],["cold","Cold (below 40°F)"],["hot","Hot (above 85°F)"]],r.climate,function(v){n.refinements.climate=v;});
      select("thermal","Personal temperature preference",[["neutral","Usual layers"],["hot","I run hot"],["cold","I run cold"]],r.thermal,function(v){n.refinements.thermal=v;});
      check("rain","Rain expected",r.rain,function(v){n.refinements.rain=v;});
      check("warmWeather","Also spending time in warmer weather",r.warmWeather,function(v){n.refinements.warmWeather=v;});
      note="The coldest outdoor conditions drive layers. Warmer weather adds shorts if needed. These are your assumptions; no live forecast is used.";
    }else if(focus==="Laundry"){
      var laundry=select("laundry","Laundry",[["no","No planned laundry"],["yes","I have planned laundry"]],r.laundry.available ? "yes":"no",function(v){n.refinements.laundry.available=v==="yes";});
      var first=number("first","First wash after how many days?",r.laundry.firstWash,60,function(v){n.refinements.laundry.firstWash=v;}),interval=number("interval","Then wash every how many days?",r.laundry.interval,60,function(v){n.refinements.laundry.interval=v;});first.min=interval.min="1";
      function laundryVisibility(){[first,interval].forEach(function(input){input.disabled=laundry.value!=="yes";input.parentNode.style.display=input.disabled ? "none":"";});}laundry.addEventListener("change",laundryVisibility);laundryVisibility();
      note="Recalculates clothing for the longest gap between washes plus a spare day. Pack extra uses this same buffer, rather than adding a second one. Contacts cover the full trip; work, dinner and suit shirts stay at full-trip quantities.";
    }else if(focus==="Activities"){
      [["hike","Hiking"],["workout","Workouts"],["water","Swimming"],["fish","Fishing"]].forEach(function(x){check(x[0],x[1],state.inputs.activities[x[0]],function(v){n.inputs.activities[x[0]]=v;});});
      check("daypack","I need a daypack",r.daypack,function(v){n.refinements.daypack=v;});
      var hike=f.querySelector("#rf-hike"),rugged=check("rugged","Rugged or wet trails",r.ruggedHike,function(v){n.refinements.ruggedHike=v;}),brooksToo=check("brooksToo","Also bring Brooks",r.brooksToo,function(v){n.refinements.brooksToo=v;});
      function hikingVisibility(){rugged.parentNode.style.display=hike.checked ? "":"none";brooksToo.parentNode.style.display=hike.checked && rugged.checked ? "":"none";}hike.addEventListener("change",hikingVisibility);rugged.addEventListener("change",hikingVisibility);hikingVisibility();
      note="Workouts assumes most days: regular T-shirts daily and shorts for two days each, adjusted for laundry. Brooks cover ordinary hikes; rugged or wet trails add hiking footwear, and Also bring Brooks makes your Brooks required alongside them. A daypack is included only when you select I need a daypack.";
    }else if(focus==="Events"){
      number("formal","Full suit days",r.formalDays,refineDays(state.inputs.start,state.inputs.end),function(v){n.refinements.formalDays=v;});
      number("dinners","Nice dinners (complete outfit)",r.dinners,refineDays(state.inputs.start,state.inputs.end),function(v){n.refinements.dinners=v;});
      note="Suit days mean jacket, suit trousers, dress shoes, belt and fresh dress shirts/socks—no undershirt. Dinner outfits are separate. After applying, we’ll walk through the outfit choices that apply.";
    }else if(focus==="Work" || focus==="Outfits & work"){
      var work=select("work","Work equipment",[["none","No work laptop"],["laptop","Laptop only / just in case"],["work","Full hotel work setup"]],r.work,function(v){n.refinements.work=v;});
      var workDays=number("workDays","Days visible on video (fresh button-up each day)",r.workDays==null ? 0:r.workDays,refineDays(state.inputs.start,state.inputs.end),function(v){n.refinements.workDays=v;});
      if(focus==="Outfits & work"){number("formal","Full suit days",r.formalDays,refineDays(state.inputs.start,state.inputs.end),function(v){n.refinements.formalDays=v;});number("dinners","Nice dinners",r.dinners,refineDays(state.inputs.start,state.inputs.end),function(v){n.refinements.dinners=v;});}
      note="Video-call days need tops only, with no dedicated bottoms. Enter zero if you don’t need work tops. Laundry does not reduce these shirts. Equipment and work tops are separate choices.";
    }else if(focus==="Dinner outfit"){
      var top=select("dinnerTop","Top for each nice dinner",[["","Choose a dinner top"],["polo","Fresh polo shirt"],["shortsleeve","Fresh short-sleeve nice shirt"],["longsleeve","Fresh long-sleeve nice shirt"],["buttonup","Fresh long-sleeve button-up (can share with work)"],["other","Other nice top"]],r.dinnerTop || "",function(v){n.refinements.dinnerTop=v;});top.required=true;
      var bottoms=select("dinnerBottoms","Suitable dinner bottoms",[["","Choose dinner bottoms"],["shorts","Reuse suitable regular Lulu shorts"],["jeans","Jeans + belt"],["khakis","Khakis + belt"],["other","Other dinner bottoms"]],r.dinnerBottoms || "",function(v){n.refinements.dinnerBottoms=v;});bottoms.required=true;
      var otherTop=inp("rf-dinnerOtherTop","text",r.dinnerOtherTop || "","Enter top name (e.g. Linen shirt)"),otherBottoms=inp("rf-dinnerOtherBottoms","text",r.dinnerOtherBottoms || "","Enter bottoms name (e.g. Dress shorts)");otherTop.maxLength=otherBottoms.maxLength=80;f.appendChild(fieldEl("Name your dinner top",otherTop));f.appendChild(fieldEl("Name your dinner bottoms",otherBottoms));
      updates.push(function(){n.refinements.dinnerOtherTop=otherTop.value.trim();n.refinements.dinnerOtherBottoms=otherBottoms.value.trim();});
      var otherBelt=check("dinnerOtherBelt","These dinner bottoms need a belt",r.dinnerOtherBelt!==false,function(v){n.refinements.dinnerOtherBelt=v;});
      function dinnerVisibility(){otherTop.parentNode.hidden=top.value!=="other";otherTop.required=top.value==="other";otherTop.disabled=top.value!=="other";otherBottoms.parentNode.hidden=bottoms.value!=="other";otherBottoms.required=bottoms.value==="other";otherBottoms.disabled=bottoms.value!=="other";otherBelt.parentNode.hidden=bottoms.value!=="other";otherTop.setCustomValidity(top.value==="other" && otherTop.value && !otherTop.value.trim() ? "Enter a name for your dinner top.":"");otherBottoms.setCustomValidity(bottoms.value==="other" && otherBottoms.value && !otherBottoms.value.trim() ? "Enter a name for your dinner bottoms.":"");}
      [top,bottoms,otherTop,otherBottoms].forEach(function(input){input.addEventListener("change",dinnerVisibility);});[otherTop,otherBottoms].forEach(function(input){input.addEventListener("input",dinnerVisibility);});dinnerVisibility();
      note="Reuse a suitable pair already on the list; add one only if missing. Jeans/khakis share one belt with suit attire. Long-sleeve button-ups can share a work shirt on the same day. Short-/long-sleeve nice shirts and Other tops get one fresh top per dinner; Other bottoms add one reusable pair. Choose for the coldest outdoor conditions: "+r.climate+".";
    }else if(focus==="Suit outfit"){
      check("tie","Include ties ("+Math.min(2,r.formalDays)+" different)",r.tie,function(v){n.refinements.tie=v;});
      check("alternateKhakis","Alternate suit trousers with khakis ("+Math.min(2,r.formalDays)+" pairs)",r.alternateKhakis,function(v){n.refinements.alternateKhakis=v;});
      check("shareSuitShirts","My solid-color shirts work for both suit and work/dinner",r.shareSuitShirts,function(v){n.refinements.shareSuitShirts=v;});
      note="One reusable suit jacket, suit trousers, dress shoes and belt. Fresh white dress shirts and dress socks per suit day; no undershirt. For multiple professional dress days, the usual rotation is two different ties and two pairs of khakis; for one day, one of each. Suit shirts stay separate from patterned work/dinner shirts unless you confirm compatibility. Khakis and the belt are shared with dinners when appropriate.";
    }else if(focus==="Shirt sharing"){
      var w=refineWardrobe(state);
      function sharing(key,label,max,value){var automatic=check(key+"Auto",label+": assume maximum overlap",value==null,function(v){n.refinements[key]=v ? null:+count.value;});var count=number(key,"How many days share a shirt?",value==null ? max:Math.min(max,value),max,function(v){if(!automatic.checked)n.refinements[key]=v;});
        function visibility(){count.disabled=automatic.checked;count.parentNode.style.display=automatic.checked ? "none":"";}automatic.addEventListener("change",visibility);visibility();f.appendChild(el("p","gen-note","Maximum shared days: "+max+". Confirm that these occasions can use the same shirt; uncheck to enter the actual overlap."));}
      if(w.overlapMax>0)f.appendChild(el("p","gen-step","Work/dinner tops: "+(w.workDays+w.dinnerButtons-w.overlapMax)+" with maximum sharing; "+(w.workDays+w.dinnerButtons)+" with separate shirts."));
      if(w.overlapMax>0)sharing("shirtOverlap","Button-up dinners share work shirts",w.overlapMax,r.shirtOverlap);
      if(w.suitMax>0)sharing("suitOverlap","Compatible suit shirts share work/dinner days",w.suitMax,r.suitOverlap);
      note="Shared shirts count once for the same day. Maximum overlap is an assumption, not a known schedule; correct it when dinners or suit days need different shirts. Laundry does not reduce these quantities.";
    }else if(focus==="Flight"){
      check("longFlight","Long international flight",r.longFlight,function(v){n.refinements.longFlight=v;});
      note="Adds international flight comfort items when Travel specifies international flying.";
    }
    var decision=refineDecisionKey(state,focus)!==null,requiredStep=refinePendingDecisions(state).indexOf(focus)>=0;
    function after(){if(flow){flow.seen[focus]=true;advance(flow);}else if(["Events","Work","Outfits & work","Weather","Dinner outfit","Suit outfit","Shirt sharing"].indexOf(focus)>=0 && refinePendingDecisions(state).length)advance({decisionsOnly:true,seen:{}});else closeSheet();}
    if(requiredStep)body.appendChild(el("p","gen-step",focus==="Laundry" ? "Long trip: confirm your laundry plan before export. Choosing No planned laundry keeps clothing for every day.":"Confirm this outfit decision before export."));else if(flow)body.appendChild(el("p","gen-step","Review one assumption at a time. Relevant outfit questions appear next."));
    f.appendChild(el("p","gen-note",note));
    if(["Work","Outfits & work","Events","Dinner outfit","Suit outfit","Shirt sharing","Laundry"].indexOf(focus)>=0){var preview=el("div","outfit-preview");preview.setAttribute("aria-live","polite");f.appendChild(preview);function showQuantities(){preview.textContent="";preview.appendChild(el("strong",null,"Quantity impact"));if(!f.checkValidity()){preview.appendChild(el("p","gen-note","Complete the fields to see the resulting quantities."));return;}updates.forEach(function(update){update();});try{var proposed=refineEvaluate(n,profile,[]);proposed.items.filter(function(x){if(focus==="Laundry")return x.section==="Clothing" && /tshirts|underwear|socks|lulu-shorts|lulu-joggers/.test(x.id);
        if(focus==="Work" || focus==="Shirt sharing")return /button-up/.test(x.id) || n.refinements.shareSuitShirts && /white-shirt/.test(x.id) || focus==="Work" && x.section==="Work";
        if(focus==="Suit outfit")return /white-shirt|suit|tie|khakis|dress-pants|dress-socks|dress-shoes|belt/.test(x.id);
        if(focus==="Dinner outfit")return (proposed.ruleResults.events || []).some(function(item){return item.id===x.id;}) && (/polo-shirts|nice-shirts|dinner-other|belt/.test(x.id) || /button-up|white-shirt/.test(x.id) && (!n.refinements.dinnerTop || n.refinements.dinnerTop==="buttonup") || /khakis/.test(x.id) && n.refinements.dinnerBottoms==="khakis" || /jeans|lulu-shorts/.test(x.id));
        return x.rule==="events";}).forEach(function(x){preview.appendChild(el("p",null,refineLabel(x)+(x.manual ? " · Manual override":"")));});if(preview.childNodes.length===1)preview.appendChild(el("p","gen-note","No items needed for this selection."));}catch(e){preview.appendChild(el("p","gen-note","Enter valid assumptions to preview."));}}f.addEventListener("input",showQuantities);f.addEventListener("change",showQuantities);showQuantities();}
    var go=el("button","btn primary",flow ? "Apply & next":"Apply & recalculate");go.type="submit";f.appendChild(go);
    if(flow && !requiredStep)f.appendChild(generatorButton("Skip for now",after));body.appendChild(f);var assumptionDraft=packingDraftAttach(f,"refine:"+t.id+":"+focus,JSON.stringify([state.inputs.start,state.inputs.end]),{contextLegacyOmit:focus==="Dinner outfit" ? ["rf-dinnerOtherTop","rf-dinnerOtherBottoms","rf-dinnerOtherBelt"]:focus==="Activities" ? ["rf-brooksToo"]:[]});
    f.addEventListener("submit",function(e){e.preventDefault();updates.forEach(function(update){update();});n.reviewed=n.reviewed||{};n.reviewed[focus]=true;
      if(decision)n.decisionReviews[focus]=refineDecisionKey(n,focus);
      if(focus==="Outfits & work")["Work","Events"].forEach(function(key){n.decisionReviews[key]=refineDecisionKey(n,key);});
      if(JSON.stringify(n.inputs)===JSON.stringify(state.inputs) && JSON.stringify(n.refinements)===JSON.stringify(state.refinements)){
        if(state.reviewed && state.reviewed[focus] && (!decision || state.decisionReviews[focus]===n.decisionReviews[focus]) && JSON.stringify(state.decisionReviews)===JSON.stringify(n.decisionReviews)){assumptionDraft.clear();after();return;}
        go.disabled=true;refinePersist(t,n,result).then(function(){assumptionDraft.clear();state=n;result=state.legacy ? refineLegacyResult(state):refineEvaluate(state,profile,[]);paint();after();}).catch(function(){go.disabled=false;failure("Could not save this review.");});return;
      }
      go.disabled=true;commit(n,[],focus+" updated").then(function(ok){if(ok){assumptionDraft.clear();after();}else go.disabled=false;});
    });
  }

  function edit(item){
    var body = openSheet("Edit this item"), f = el("form","form gen-form"), label=inp("ri-label","text",item.label), quantity=inp("ri-quantity","number",item.quantity),section=sel("ri-section",REFINE_ORDER.filter(function(x){return x!=="Before leaving";}).concat(REFINE_ORDER.indexOf(item.section)<0 ? [item.section]:[]).map(function(x){return [x,x];}),item.section); label.required=true; quantity.required=true; quantity.min="1"; quantity.max="999";
    f.appendChild(fieldEl("Item",label)); f.appendChild(fieldEl("Quantity",quantity));f.appendChild(fieldEl("Section / toiletries bag",section)); f.appendChild(el("p","muted","This creates a pinned manual override. Refinements will preserve it until you choose Return to automatic.")); var go=el("button","btn primary","Save override");go.type="submit";f.appendChild(go);body.appendChild(f);var itemDraft=packingDraftAttach(f,"edit:"+t.id+":"+item.id,JSON.stringify([item.label,item.quantity,item.section]),{contextLegacyOmit:["ri-section"],legacyContexts:/^(Dry|Liquid) toiletries$/.test(item.section) ? [JSON.stringify([item.label,item.quantity,"Toiletries"])]:[]});
    f.addEventListener("submit",function(e){e.preventDefault();var next=clone(state); var value=Object.assign({},item,{label:label.value.trim(),quantity:+quantity.value,section:section.value}); if(next.overrides.added[item.id])next.overrides.added[item.id]=value;else next.overrides.edited[item.id]=value;commit(next,[],"Manual item override saved").then(function(ok){if(ok){itemDraft.clear();closeSheet();}});});
  }
  function remove(item){ var body=openSheet("Remove "+item.label); body.appendChild(el("p",null,item.critical || item.required ? "This item supports a critical or required need. Removing it will leave a visible warning; account for a replacement." : "Remove only for this trip, or change your future packing defaults."));
    body.appendChild(generatorButton("Remove for this trip",function(){var next=clone(state);next.overrides.removed[item.id]=true;commit(next,[],"Removed for this trip").then(function(ok){if(ok)closeSheet();});},true));
    if(!item.critical && !item.required && !item.manual)body.appendChild(generatorButton("Usually don’t pack this",function(){ if(busy)return;var oldProfile=clone(profile),p=refineExclude(profile,item);db.doc("meta/packing").set(p).then(function(){var next=clone(state);next.overrides.removed[item.id]=true;return commit(next,["profile"],"Default exclusion saved; inspect or reset it in Packing preferences",oldProfile);}).then(function(ok){if(ok)closeSheet();else return db.doc("meta/packing").set(oldProfile).then(function(){profile=oldProfile;error.textContent="The trip could not be saved; the default exclusion was rolled back.";}).catch(function(){error.textContent="The default exclusion was saved but the trip change failed. Reset the exclusion in Packing preferences.";});}).catch(function(){error.textContent="Could not save the default exclusion.";}); }));
  }
  function add(){var body=openSheet("Add an edge-case item"),f=el("form","form gen-form"),label=inp("ra-label","text",""),quantity=inp("ra-quantity","number",1),section=sel("ra-section",REFINE_ORDER.filter(function(x){return x!=="Before leaving";}).map(function(x){return [x,x];}),"Personal bag & day gear");label.required=true;quantity.required=true;quantity.min="1";quantity.max="999";f.appendChild(fieldEl("Item",label));f.appendChild(fieldEl("Quantity",quantity));f.appendChild(fieldEl("Section",section));var go=el("button","btn primary","Add item");go.type="submit";f.appendChild(go);body.appendChild(f);var addDraft=packingDraftAttach(f,"add:"+t.id);f.addEventListener("submit",function(e){e.preventDefault();var next=clone(state),id="manual:"+Date.now().toString(36);next.overrides.added[id]={id:id,label:label.value.trim(),quantity:+quantity.value,section:section.value};commit(next,[],"Manual item added").then(function(ok){if(ok){addDraft.clear();closeSheet();}});});}
  // Standalone app: explanations live in one section, keeping individual list rows compact.
  function rules(){
    var body=openSheet("Packing rules");body.appendChild(el("p","muted","Rules currently applied to this trip. Refinements update these automatically; manual overrides remain pinned. Manage your usual items and exclusions in Packing preferences."));
    result.groups.forEach(function(group){var reasons=[];group.items.forEach(function(item){(item.reasons || []).forEach(function(reason){if(reasons.indexOf(reason)<0)reasons.push(reason);});});
      if(!reasons.length)return;var section=el("section","stack");section.appendChild(el("h3",null,group.title));var list=el("ul","gen-summary");reasons.forEach(function(reason){list.appendChild(el("li",null,reason));});section.appendChild(list);body.appendChild(section);
    });
  }
  function paint(){
    chips.textContent="";var pending=refinePendingDecisions(state);outfitSummary();
    var status=el("p","trip-plan-progress",pending.length ? pending.length+(pending.indexOf("Laundry")>=0 ? (pending.length===1 ? " choice to confirm":" choices to confirm"):(pending.length===1 ? " outfit choice to confirm":" outfit choices to confirm")):state.legacy ? "Saved list · automatic refinement is off":state.refinements.climate==="unknown" ? "Required outfit choices complete · weather provisional":"Required outfit choices complete");status.setAttribute("role","status");chips.appendChild(status);tripPlan(pending);
    var addButton=generatorButton("+ Add an edge-case item",add);addButton.id="rr-add";chips.appendChild(addButton);
    packingLearningObserve(t,state,result).then(function(){learningNotice.textContent="";var suggestions=packingLearningEditRecommendations(packingLearningLoad(),generatorPrefs());if(suggestions.length){learningNotice.appendChild(el("p","gen-note","Learning noticed "+suggestions.length+" recurring packing choice(s). Review suggested defaults; nothing changes silently."));learningNotice.appendChild(generatorButton("Review suggestions",packingLearningSheet));}}).catch(function(){learningNotice.textContent="Automatic learning could not save on this device. Your trip is still saved.";});
    var visibleWarnings=result.warnings.filter(function(x){return x.id!=="weather" && (!x.decision || pending.indexOf(x.decision)<0);});warnings.textContent="";if(visibleWarnings.length){var warning=el("details","panel refine-warning");warning.open=true;warning.appendChild(el("summary",null,"Check assumptions · "+visibleWarnings.length));visibleWarnings.forEach(function(x){var row=el("p",null,x.text);if(x.decision)row.appendChild(generatorButton("Confirm",function(){assumptions(x.decision,{decisionsOnly:true,seen:{}});}));if(x.itemId && state.overrides.removed[x.itemId])row.appendChild(generatorButton("Restore",function(){var next=clone(state);delete next.overrides.removed[x.itemId];commit(next,[],"Required item restored");}));warning.appendChild(row);});warnings.appendChild(warning);}
    if(Object.keys(state.overrides.removed).length){var removed=el("details","panel");removed.appendChild(el("summary",null,"Removed for this trip · "+Object.keys(state.overrides.removed).length));Object.keys(state.overrides.removed).forEach(function(id){var item=result.ruleResults && Object.keys(result.ruleResults).flatMap(function(k){return result.ruleResults[k];}).find(function(x){return x.id===id;}) || state.overrides.added[id];var row=el("div","gen-actions");row.appendChild(el("span",null,item ? item.label : id));row.appendChild(generatorButton("Return to automatic",function(){var next=clone(state);delete next.overrides.removed[id];delete next.overrides.edited[id];commit(next,[],"Trip removal reset (profile exclusions still apply)");}));removed.appendChild(row);});warnings.appendChild(removed);}
    var alive={};result.groups.forEach(function(g){var signature=JSON.stringify(g),node=sectionNodes[g.title];alive[g.title]=true;if(!node){node=el("section","panel");sectionNodes[g.title]=node;}if(sectionSignatures[g.title]!==signature){node.textContent="";node.appendChild(el("h3",null,g.title));g.items.forEach(function(item){var row=el("div","refine-item");row.dataset.itemId=item.id;var copy=el("div","refine-item-copy");copy.appendChild(el("strong",null,refineLabel(item)));if(item.manual)copy.appendChild(el("span","refine-badge","Manual override"));row.appendChild(copy);if(!g.depart){var controls=el("div","gen-actions");controls.appendChild(generatorButton("Edit",function(){edit(item);}));controls.appendChild(generatorButton("Remove",function(){remove(item);}));if(state.overrides.edited[item.id] || (!state.legacy && state.overrides.added[item.id] && state.overrides.added[item.id].legacy && Object.keys(result.ruleResults).some(function(k){return result.ruleResults[k].some(function(x){return x.id===item.id;});})))controls.appendChild(generatorButton("Return to automatic",function(){var next=clone(state);delete next.overrides.edited[item.id];if(next.overrides.added[item.id] && next.overrides.added[item.id].legacy)delete next.overrides.added[item.id];commit(next,[],"Manual override reset");}));row.appendChild(controls);}node.appendChild(row);});sectionSignatures[g.title]=signature;}list.appendChild(node);});Object.keys(sectionNodes).forEach(function(title){if(!alive[title]){sectionNodes[title].remove();delete sectionNodes[title];delete sectionSignatures[title];}});
    if(state.undo && !summary.childNodes.length)summary.appendChild(generatorButton("Undo last change",undo));
  }
  paint();return root;
}
function refineProfileSheet(){generatorPreferences();}
