// Builds the Dashboard's scoped copies of the standalone packing generator CSS.
// usage: node scope-css.mjs <travel-apps dir> <dashboard dir>
// Writes <dashboard>/js/packgen/{base,app,generator}.css:
//   base.css      = rules of travel-apps/shared/styles.css that differ from the Dashboard's styles.css (standalone fonts/sizes)
//   app.css       = travel-apps/shared/app.css
//   generator.css = travel-apps/packing-list/generator.css
// every selector scoped under .packgen (the Packing tab root and generator sheets), so nothing else in the Dashboard changes.
import {readFile, writeFile} from 'node:fs/promises';
import {join} from 'node:path';
const [ta, dash] = process.argv.slice(2);

function strip(css){ return css.replace(/\/\*[\s\S]*?\*\//g, ''); }
// Parse into [{prelude, body}] where at-rule blocks have children.
function parse(css){
  const out = []; let i = 0;
  function block(){ const items = [];
    while (i < css.length){
      const close = css.indexOf('}', i), open = css.indexOf('{', i);
      if (close >= 0 && (open < 0 || close < open)){ i = close + 1; return items; }
      if (open < 0) { i = css.length; break; }
      const prelude = css.slice(i, open).trim(); i = open + 1;
      if (prelude.startsWith('@media') || prelude.startsWith('@supports')){ items.push({prelude, children:block()}); }
      else { const end = css.indexOf('}', i); items.push({prelude, body:css.slice(i, end).trim()}); i = end + 1; }
    }
    return items; }
  return block();
}
function splitSel(s){ const out = []; let depth = 0, cur = '';
  for (const ch of s){ if (ch === '(' || ch === '[') depth++; else if (ch === ')' || ch === ']') depth--; if (ch === ',' && !depth){ out.push(cur.trim()); cur = ''; } else cur += ch; }
  if (cur.trim()) out.push(cur.trim()); return out; }
const S = '.packgen';
function scopeOne(sel){
  if (/packing-delete-toast/.test(sel)) return sel;                 // the Delete-list toast lives on <body>; its class is generator-only
  if (sel === ':root' || sel === 'html' || sel === 'body') return S;
  let m = /^(:root[^\s]*)(\s+(.*))?$/.exec(sel);
  if (m) return m[3] ? `${m[1]} ${S} ${m[3]}` : `${m[1]} ${S}`;
  if (/^body\s/.test(sel)) return S + ' ' + sel.replace(/^body\s+/, '');
  if (sel === '#view') return '#packgen';
  if (/^\.sheet-bg\b/.test(sel)) return '.sheet-bg' + S + sel.slice('.sheet-bg'.length);
  return S + ' ' + sel;
}
// body: keep typography only (no page background/height on the tab root or sheet backdrops).
function bodyDecls(body){ return body.split(';').map(x => x.trim()).filter(Boolean).filter(d => /^(font|line-height|letter-spacing|-webkit-font-smoothing|color)\b/.test(d)).join(';'); }
function emit(items, filter){
  return items.map(it => {
    if (it.children){ const inner = emit(it.children, filter); return inner.trim() ? `${it.prelude}{\n${inner}\n}` : ''; }
    if (filter && !filter(it)) return '';
    const sels = splitSel(it.prelude); let body = it.body;
    if (sels.length === 1 && sels[0] === 'body'){ body = bodyDecls(body); if (!body) return ''; }
    return sels.map(scopeOne).join(',') + '{' + body + '}';
  }).filter(Boolean).join('\n');
}
function flat(items, ctx = '', out = []){ items.forEach(it => it.children ? flat(it.children, ctx + it.prelude, out) : out.push(ctx + '|' + it.prelude.replace(/\s+/g, ' ') + '|' + it.body.replace(/\s+/g, ' '))); return out; }
function flatFilter(items, keep, ctx = ''){ return items.map(it => it.children ? {prelude:it.prelude, children:flatFilter(it.children, keep, ctx + it.prelude)} : (keep.has(ctx + '|' + it.prelude.replace(/\s+/g, ' ') + '|' + it.body.replace(/\s+/g, ' ')) ? null : it)).filter(Boolean); }

const head = (src) => `/* GENERATED by dash-test/tools/scope-css.mjs from ${src} — do not edit by hand; re-run the tool after re-porting.\n   Every selector is scoped under .packgen (Packing tab root and generator sheets) so the rest of the Dashboard is unchanged. */\n`;
const shared = parse(strip(await readFile(join(ta, 'shared/styles.css'), 'utf8'))), dashCss = parse(strip(await readFile(join(dash, 'styles.css'), 'utf8')));
const same = new Set(flat(dashCss)), delta = flatFilter(shared, same);
const root = `/* Packing tab root: the standalone's #view column and body typography. */\n#packgen{display:flex;flex-direction:column;gap:16px;min-width:0;}\n`;
await writeFile(join(dash, 'js/packgen/base.css'), head('travel-apps/shared/styles.css (only rules that differ from the Dashboard styles.css)') + root + emit(delta) + '\n');
await writeFile(join(dash, 'js/packgen/app.css'), head('travel-apps/shared/app.css') + emit(parse(strip(await readFile(join(ta, 'shared/app.css'), 'utf8')))) + '\n');
await writeFile(join(dash, 'js/packgen/generator.css'), head('travel-apps/packing-list/generator.css') + emit(parse(strip(await readFile(join(ta, 'packing-list/generator.css'), 'utf8')))) + '\n');
console.log('delta rules:', flat(delta).length);
