// Focused regression checks for reusable test scenarios and refinement review.
import http from 'node:http';import {readFile} from 'node:fs/promises';import {join,dirname,extname} from 'node:path';import {fileURLToPath} from 'node:url';
let pw;try{pw=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');}catch{console.log('SKIP: playwright not installed');process.exit(0);}
const root=join(dirname(fileURLToPath(import.meta.url)),'..'),server=http.createServer(async(req,res)=>{let path=req.url.split('?')[0];if(path.endsWith('/'))path+='index.html';try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'})[extname(path)] || 'application/octet-stream');res.end(await readFile(join(root,path)));}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=process.env.PACKING_BASE_URL || `http://127.0.0.1:${server.address().port}/packing-list/`,browser=await pw.chromium.launch({executablePath:process.env.CHROMIUM_PATH || undefined}),p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
function assert(value,message){if(!value)throw new Error(message);}
try{
  await p.goto(base+'?test=1#new');await p.waitForSelector('#rs-style');await p.selectOption('#rs-style','longer-trip');await p.fill('#rs-where','Unfinished destination');await p.check('#rs-workout');
  await p.locator('.rp-sum button').first().click();for(let n=0;n<24;n++){const m=await p.locator('.rp-head b').textContent();if(m==='October 2026')break;await p.locator('.rp-head button').nth(new Date(m+' 1')<new Date(2026,9,1) ? 1:0).click();}await p.locator('.rp-grid button[aria-label*="Oct 8"]').click();await p.locator('.rp-grid button[aria-label*="Oct 14"]').click();await p.getByRole('button',{name:'OK',exact:true}).click();
  await p.check('#rs-occasions');await p.fill('#rs-formalDays','2');await p.reload();await p.waitForSelector('#rs-where');assert(await p.inputValue('#rs-formalDays')==='2','autosave lost entered suit days');await p.fill('#rs-formalDays','');
  await p.reload();await p.waitForSelector('#rs-where');assert(await p.inputValue('#rs-formalDays')==='0','restored blank suit days did not default to zero');assert(await p.inputValue('#rs-where')==='Unfinished destination' && await p.inputValue('#rs-style')==='longer-trip' && await p.locator('#rs-workout').isChecked(),'setup draft not restored');assert((await p.textContent('.rp-hint')).includes('7 days'),'calendar dates not restored');assert((await p.textContent('.rs-form')).includes('Restored your unfinished draft'),'missing restore status');
  await p.click('button:has-text("Generate my list")');await p.waitForSelector('#rr-export');assert(await p.evaluate(()=>refineLoad(route().t).refinements.laundry.available),'restored style lost laundry');assert(!await p.evaluate(()=>localStorage.getItem(packingDraftPath('setup:new'))),'applied setup draft retained');
  await p.click('#rr-adjust');await p.click('button:has-text("Laundry:")');await p.fill('#rf-first','2');await p.fill('#rf-interval','2');await p.click('button:has-text("Close")');assert(await p.evaluate(()=>refineLoad(route().t).refinements.laundry.firstWash)===4,'draft changed confirmed assumptions');await p.reload();await p.waitForSelector('#rr-export');await p.click('#rr-adjust');await p.click('button:has-text("Laundry:")');assert(await p.inputValue('#rf-first')==='2' && await p.inputValue('#rf-interval')==='2','refinement draft not restored');await p.click('button:has-text("Apply & recalculate")');await p.waitForSelector('.sheet-bg',{state:'detached'});assert(await p.evaluate(()=>refineLoad(route().t).refinements.laundry.firstWash)===2,'restored refinement not applied');
  await p.locator('[data-item-id="pack:tshirts"]').getByRole('button',{name:'Edit',exact:true}).click();await p.fill('#ri-quantity','9');await p.click('button:has-text("Close")');await p.reload();await p.waitForSelector('#rr-export');await p.locator('[data-item-id="pack:tshirts"]').getByRole('button',{name:'Edit',exact:true}).click();assert(await p.inputValue('#ri-quantity')==='9','manual edit draft lost');assert(!await p.evaluate(()=>refineLoad(route().t).overrides.edited['pack:tshirts']),'manual draft applied without confirmation');await p.click('button:has-text("Save override")');await p.waitForSelector('.sheet-bg',{state:'detached'});
  await p.click('#rr-add');await p.fill('#ra-label','Camera');await p.fill('#ra-quantity','3');await p.click('button:has-text("Close")');await p.click('#rr-add');assert(await p.inputValue('#ra-label')==='Camera' && await p.inputValue('#ra-quantity')==='3','addition draft lost');await p.click('button:has-text("Discard unfinished draft")');assert(await p.inputValue('#ra-label')==='' && !await p.evaluate(()=>localStorage.getItem(packingDraftPath('add:'+route().t.id))),'discard did not clear draft');await p.click('button:has-text("Close")');
  await p.evaluate(()=>generatorPreferences());await p.getByText('Add usual item',{exact:true}).click();await p.fill('#gp-addName','Unfinished usual item');await p.check('#gp-addAlways');await p.getByRole('button',{name:'Add item',exact:true}).click();await p.getByLabel('Include Water bottle',{exact:true}).uncheck();await p.click('button:has-text("Close")');await p.reload();await p.waitForSelector('#rr-export');await p.evaluate(()=>generatorPreferences());assert(await p.getByLabel('Always bring Unfinished usual item',{exact:true}).isChecked() && !await p.getByLabel('Include Water bottle',{exact:true}).isChecked(),'preference draft lost');assert(!await p.evaluate(()=>(generatorPrefs().generatorExtras || []).includes('Unfinished usual item')),'preference draft silently saved');await p.click('button:has-text("Save my preferences")');await p.waitForSelector('.sheet-bg',{state:'detached'});assert(await p.evaluate(()=>generatorPrefs().generatorExtras.includes('Unfinished usual item')),'preference confirmation failed');
  await p.getByText('Trip styles & learning',{exact:true}).click();await p.click('button:has-text("Save trip style")');await p.fill('#ps-name','Unfinished style');await p.click('button:has-text("Close")');await p.click('button:has-text("Save trip style")');assert(await p.inputValue('#ps-name')==='Unfinished style','style name draft lost');await p.click('button:has-text("Discard unfinished draft")');await p.click('button:has-text("Close")');
  await p.click('button:has-text("Learn from this trip")');await p.selectOption('#pl-item','pack:wrinkle-release');await p.click('button:has-text("Add feedback")');await p.click('button:has-text("Close")');await p.reload();await p.waitForSelector('#rr-export');await p.getByText('Trip styles & learning',{exact:true}).click();await p.click('button:has-text("Learn from this trip")');assert((await p.textContent('.sheet-body')).includes('Wrinkle release · unneeded'),'feedback exceptions draft lost before any export');assert(!await p.evaluate(()=>Object.values(packingLearningLoad().trips).some(x=>x.reviewedAt)),'feedback draft became learning evidence');await p.click('button:has-text("Discard unfinished draft")');assert(!(await p.textContent('.sheet-body')).includes('Wrinkle release · unneeded'),'discard retained feedback exceptions');await p.click('button:has-text("Close")');
  await p.goto(base+'?test=1#new');await p.waitForSelector('#rs-where');await p.evaluate(()=>{window.autosaveSet=localStorage.setItem.bind(localStorage);localStorage.setItem=function(){throw new Error('Injected blocked storage');};});await p.fill('#rs-where','Blocked draft');assert((await p.textContent('.rs-form')).includes('Draft could not be saved'),'draft storage failure hidden');await p.evaluate(()=>localStorage.setItem=window.autosaveSet);await p.fill('#rs-where','Sandbox draft');
  const real=await browser.newPage();await real.goto(base+'#new');await real.waitForSelector('#rs-where');assert(await real.inputValue('#rs-where')==='','sandbox draft leaked into real setup');await real.close();
  for(const width of [360,390,430])for(const colorScheme of ['light','dark']){await p.setViewportSize({width,height:844});await p.emulateMedia({colorScheme});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'autosave mobile overflow');}
  assert(errors.length===0,errors.join('; '));console.log('OK: immediate draft autosave, calendar/style resume, refinements, overrides, preferences, discard, failures and namespace isolation');
}catch(e){console.error(e.stack || e.message);process.exitCode=1;}finally{await browser.close();server.close();}
