// Automatic edit learning uses the real generator screen and remains separate from actual-use feedback.
import http from 'node:http';import {readFile} from 'node:fs/promises';import {join,dirname,extname} from 'node:path';import {fileURLToPath} from 'node:url';
let pw;try{pw=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');}catch{console.log('SKIP: playwright not installed');process.exit(0);}
const root=join(dirname(fileURLToPath(import.meta.url)),'..'),server=http.createServer(async(req,res)=>{let path=req.url.split('?')[0];if(path.endsWith('/'))path+='index.html';try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'})[extname(path)] || 'application/octet-stream');res.end(await readFile(join(root,path)));}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=process.env.PACKING_BASE_URL || `http://127.0.0.1:${server.address().port}/packing-list/`,browser=await pw.chromium.launch({executablePath:process.env.CHROMIUM_PATH || undefined}),p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
function assert(value,message){if(!value)throw new Error(message);}
try{
  await p.goto(base+'?test=1');await p.waitForSelector('#view');await p.waitForFunction(()=>typeof packingLearningObserve==='function');
  await p.evaluate(async()=>{for(var n=0;n<5;n++){var t={id:'LEARN-'+n,name:'Comparable trip '+n,where:'Phoenix',start:'2026-09-01',end:'2026-09-04'},state=refineNewState(t,{climate:'mild'});if(n<4)state.overrides.removed['pack:wrinkle-release']=true;var result=refineEvaluate(state,generatorPrefs(),[]);await db.doc('trips/'+t.id).set(t);await refinePersist(t,state,result);await packingLearningObserve(t,state,result);}});
  await p.goto(base+'?test=1#LEARN-4');await p.waitForSelector('#rr-export');await p.waitForSelector('button:has-text("Review suggestions")');assert(await p.locator('.refine-one').count()===0 && await p.locator('#rr-adjust').count()===1,'repetitive assumptions still on list');assert(!await p.evaluate(()=>generatorPrefs().refinementProfile?.excluded?.['pack:wrinkle-release']),'pattern silently applied');assert(await p.evaluate(()=>Object.keys(packingLearningLoad().trips).length)===0,'edit observation invented actual-use reports');
  for(const width of [360,390,430]){await p.setViewportSize({width,height:844});assert(await p.evaluate(()=>{var row=document.querySelector('[data-item-id="pack:water-bottle"]'),copy=row.querySelector('.refine-item-copy').getBoundingClientRect(),controls=row.querySelector('.gen-actions').getBoundingClientRect();return Math.abs(copy.top-controls.top)<2 && [...row.querySelectorAll('button')].every(b=>b.getBoundingClientRect().height>=44) && document.documentElement.scrollWidth<=innerWidth;}),'short rows should keep controls beside the label with 44px targets');}
  await p.locator('[data-item-id="pack:wrinkle-release"]').getByRole('button',{name:'Remove',exact:true}).click();await p.click('button:has-text("Remove for this trip")');await p.waitForSelector('.sheet-bg',{state:'detached'});await p.waitForFunction(()=>packingLearningLoad().editTrips['LEARN-4'].items['pack:wrinkle-release'].change==='removed');await p.getByRole('button',{name:'Undo',exact:true}).click();await p.waitForFunction(()=>packingLearningLoad().editTrips['LEARN-4'].items['pack:wrinkle-release'].change==='kept');
  await p.click('button:has-text("Review suggestions")');assert((await p.textContent('.sheet-body')).includes('Automatic learning from edits'),'automatic patterns not inspectable');await p.getByText('Saved edit history · 5 trips',{exact:true}).click();assert((await p.textContent('.sheet-body')).includes('Comparable trip 0'),'history missing trip labels');await p.getByRole('button',{name:'Review default change',exact:true}).click();await p.click('button:has-text("Apply default exclusion")');await p.waitForFunction(()=>generatorPrefs().refinementProfile.excluded['pack:wrinkle-release']);
  await p.evaluate(async()=>{for(var n=0;n<3;n++){var t=TRIPS['LEARN-'+n],state=refineLoad(t);state.overrides.added['manual:camera']={id:'manual:camera',label:'Camera',quantity:1,section:'Personal bag & day gear'};await packingLearningObserve(t,state,refineEvaluate(state,generatorPrefs(),[]));}packingLearningSheet();});
  var camera=p.locator('.sheet-body section.panel').filter({has:p.getByText('Camera',{exact:true})});await camera.getByRole('button',{name:'Dismiss this pattern',exact:true}).click();assert(!await p.locator('.sheet-body section.panel').filter({has:p.getByText('Camera',{exact:true})}).count(),'dismissed suggestion still shown');
  await p.getByText('Dismissed patterns · 1',{exact:true}).click();await p.getByRole('button',{name:'Restore suggestion',exact:true}).click();camera=p.locator('.sheet-body section.panel').filter({has:p.getByText('Camera',{exact:true})});await camera.getByRole('button',{name:'Review Packing preferences',exact:true}).click();assert(await p.getByLabel('Always bring Camera',{exact:true}).isChecked(),'addition action did not prefill preferences');assert(!await p.evaluate(()=>generatorPrefs().generatorExtras?.includes('Camera')),'prefill silently saved');await p.getByRole('button',{name:'Save my preferences',exact:true}).click();await p.evaluate(()=>packingLearningSheet());assert(!await p.locator('.sheet-body section.panel').filter({has:p.getByText('Camera',{exact:true})}).count(),'adopted addition remained suggested');
  await p.evaluate(async()=>{var t={id:'SUIT-PREVIEW',name:'Suit preview',where:'Phoenix',start:'2026-10-08',end:'2026-10-12'},s=refineNewState(t,{climate:'hot',formal:2});await db.doc('trips/'+t.id).set(t);await refinePersist(t,s,refineEvaluate(s,generatorPrefs(),[]));closeSheet();location.hash=t.id;});await p.waitForSelector('#rr-adjust');await p.getByRole('button',{name:'Outfits & work',exact:true}).click();await p.getByRole('button',{name:/^Suit outfit:/}).click();assert((await p.textContent('.outfit-preview')).includes('White dress shirts ×2'),'suit preview omitted stable white-shirt ID');assert(!/Underwear|T-shirts/.test(await p.textContent('.outfit-preview')),'suit preview showed unrelated clothing');await p.evaluate(()=>packingLearningSheet());
  await p.getByRole('button',{name:'Reset learning history',exact:true}).click();await p.getByRole('button',{name:'Reset learning history',exact:true}).click();await p.waitForFunction(()=>packingLearningLoad().observeEdits===false);assert(await p.evaluate(()=>Object.keys(packingLearningLoad().editTrips).length)===0,'reset retained observed edit history');assert(await p.evaluate(()=>generatorPrefs().refinementProfile.excluded['pack:wrinkle-release']),'learning reset removed applied defaults');
  for(const width of [360,390,430])for(const colorScheme of ['light','dark']){await p.setViewportSize({width,height:844});await p.emulateMedia({colorScheme});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'learning sheet overflow');}
  assert(errors.length===0,errors.join('; '));console.log('OK: central trip plan, automatic edit observation, undo evidence, visible suggestions, approved defaults, reset and mobile layout');
}catch(e){console.error(e.stack || e.message);process.exitCode=1;}finally{await browser.close();server.close();}
