// Consolidated menus must preserve old defaults, drafts and deterministic refinement behavior.
import http from 'node:http';import {readFile} from 'node:fs/promises';import {join,dirname,extname} from 'node:path';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
let pw;try{pw=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');}catch{console.log('SKIP: playwright not installed');process.exit(0);}
const root=join(dirname(fileURLToPath(import.meta.url)),'..'),server=http.createServer(async(req,res)=>{let path=req.url.split('?')[0];if(path.endsWith('/'))path+='index.html';try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'})[extname(path)] || 'application/octet-stream');res.end(await readFile(join(root,path)));}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=process.env.PACKING_BASE_URL || `http://127.0.0.1:${server.address().port}/packing-list/`,browser=await pw.chromium.launch({executablePath:process.env.CHROMIUM_PATH || undefined}),p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
const button=name=>p.getByRole('button',{name,exact:true});
async function addUsual(name,section,always){await p.locator('.sheet-body details').filter({has:p.getByText('Add usual item',{exact:true})}).evaluate(x=>x.open=true);await p.fill('#gp-addName',name);await p.selectOption('#gp-addSection',section);await p.locator('#gp-addAlways').setChecked(always);await button('Add item').click();}
try{
  await p.goto(base+'?test=1#new');await p.waitForSelector('#rs-where');assert.equal(await p.locator('select#rs-type').count(),0);assert.equal(await p.locator('#rs-occasions').count(),1);assert(await p.evaluate(()=>!!(document.querySelector('#rs-workout').compareDocumentPosition(document.querySelector('#rs-occasions'))&Node.DOCUMENT_POSITION_FOLLOWING)),'activities must precede outfits');assert(!await p.locator('.rs-optional').evaluate(x=>x.open),'optional settings not collapsed');await p.locator('.rs-optional > summary').click();await p.selectOption('#rs-climate','hot');await p.check('#rs-extra-kindle');await p.locator('.rs-optional > summary').click();await p.reload();await p.waitForSelector('#rs-where');assert.equal(await p.inputValue('#rs-climate'),'hot');assert(await p.isChecked('#rs-extra-kindle'),'collapsed optional settings lost their draft');assert(await p.locator('.rs-optional').evaluate(x=>x.open),'restored optional choices should be visible');await p.check('#rs-occasions');assert.equal(await p.inputValue('#rs-work'),'none');for(const id of ['workDays','formalDays','dinners'])assert.equal(await p.inputValue('#rs-'+id),'0');
  await p.evaluate(async()=>{var profile=clone(PACK_PREFS);profile.generatorExtras=['Medicine pouch'];profile.refinementProfile={excluded:{'pack:wrinkle-release':'Wrinkle release'}};await db.doc('meta/packing').set(profile);var t={id:'MENUS',name:'Menu regression',where:'Phoenix',start:'2026-10-08',end:'2026-10-12',bookings:{keep:{note:'Keep booking'}}},s=refineNewState(t,{tripType:'mixed',climate:'hot',work:'laptop',workDays:3,formal:2,dinners:2});s.refinements.dinnerTop='polo';s.refinements.dinnerBottoms='khakis';['Work','Events','Dinner outfit','Suit outfit','Shirt sharing'].forEach(k=>s.decisionReviews[k]=refineDecisionKey(s,k));var result=refineEvaluate(s,profile,[]);s.overrides.edited['pack:tshirts']=Object.assign({},result.items.find(x=>x.id==='pack:tshirts'),{quantity:10});await db.doc('trips/'+t.id).set(t);await refinePersist(t,s,refineEvaluate(s,profile,[]));location.hash=t.id;});
  await p.waitForSelector('#rr-adjust');const menu=await p.locator('.trip-plan-title').allTextContents();assert.deepEqual(menu,['Travel','Activities','Outfits & work','Weather','Laundry','Packing','Trip extras']);assert.equal(await p.getByRole('button',{name:'Adjust trip',exact:true}).count(),0,'old menu still visible');for(const width of [360,390,430])for(const colorScheme of ['light','dark']){await p.setViewportSize({width,height:844});await p.emulateMedia({colorScheme});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'trip plan overflow');assert(await p.locator('.trip-plan-card').evaluateAll(xs=>xs.every(x=>x.getBoundingClientRect().height>=44)),'small card tap targets');}await button('Activities').click();await p.check('#rf-workout');await button('Apply & recalculate').click();await p.waitForSelector('.sheet-bg',{state:'detached'});assert.match(await button('Activities').textContent(),/workouts/);assert.match(await p.locator('[data-item-id="pack:tshirts"]').textContent(),/×10/);await p.getByRole('link',{name:'Trip details: destination, dates & travel',exact:true}).click();await p.waitForSelector('#rs-where');for(const id of ['rs-climate','rs-workDays','rs-hike','rs-style'])assert.equal(await p.locator('#'+id).count(),0,'trip details duplicated '+id);
  await p.fill('#rs-where','Mesa');await p.selectOption('#rs-bag','checked');await p.locator('.rp-sum button').nth(1).click();await p.locator('.rp-grid button[aria-label*="Oct 13"]').click();await button('OK').click();await button('Update trip & recalculate').click();await p.waitForSelector('#rr-export');let saved=await p.evaluate(()=>({trip:TRIPS.MENUS,state:refineLoad(TRIPS.MENUS)}));assert.equal(saved.trip.where,'Mesa');assert.equal(saved.trip.end,'2026-10-13');assert.equal(saved.trip.bookings.keep.note,'Keep booking');assert.equal(saved.state.inputs.tripType,'mixed');assert.equal(saved.state.refinements.workDays,3);assert.equal(saved.state.overrides.edited['pack:tshirts'].quantity,10);
  await button('Undo last change').click();await p.waitForFunction(()=>TRIPS.MENUS.where==='Phoenix' && TRIPS.MENUS.end==='2026-10-12');assert.equal(await p.evaluate(()=>refineLoad(TRIPS.MENUS).inputs.end),'2026-10-12','Undo left trip dates and engine out of sync');
  await button('Outfits & work').click();assert.equal(await p.locator('.sheet-body button:has-text("Days & work equipment")').count(),1);await button('Days & work equipment').click();await p.fill('#rf-dinners','3');await button('Apply & recalculate').click();await p.waitForSelector('#rf-dinnerTop');assert.equal(await p.locator('#rf-workDays,#rf-formal').count(),0,'count questions repeated after unified count edit');await button('Apply & next').click();await p.waitForSelector('#rr-outfitSummary');await button('Review full list').click();assert.match(await p.locator('[data-item-id="pack:polo-shirts"]').textContent(),/×3/);assert.match(await p.locator('[data-item-id="pack:tshirts"]').textContent(),/×10/);
  await button('Packing preferences').click();assert.equal(await p.locator('#gp-custom').isVisible(),false);assert.equal(await p.locator('.sheet-body input[aria-label^="Add item to"]').count(),0);assert(await p.getByLabel('Always bring Medicine pouch',{exact:true}).isChecked());assert(!await p.getByLabel('Include Wrinkle release',{exact:true}).isChecked());await p.getByLabel('Include Wrinkle release',{exact:true}).check();assert(await p.evaluate(()=>!!generatorPrefs().refinementProfile.excluded['pack:wrinkle-release']),'preferences changed before confirmation');
  await addUsual('Camera','Personal bag & day gear',false);await addUsual('Lens cleaner','Liquid toiletries',true);
  for(const width of [360,390,430])for(const colorScheme of ['light','dark']){await p.setViewportSize({width,height:844});await p.emulateMedia({colorScheme});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'preferences overflow');assert(await p.locator('.sheet-body input[type=text],.sheet-body select').evaluateAll(xs=>xs.every(x=>parseFloat(getComputedStyle(x).fontSize)>=16)),'small fields cause iPhone zoom');}
  await button('Save my preferences').click();await p.waitForSelector('.sheet-bg',{state:'detached'});const current=await p.evaluate(()=>{var profile=generatorPrefs(),items=refineEvaluate(refineLoad(TRIPS.MENUS),profile,[]).items;return {profile:profile,medicine:items.find(x=>x.label==='Medicine pouch'),lens:items.find(x=>x.label==='Lens cleaner'),camera:items.find(x=>x.label==='Camera')};});assert(current.medicine.required);assert(current.lens.required);assert.equal(current.lens.section,'Liquid toiletries');assert(!current.camera.required);assert(!current.profile.refinementProfile.excluded['pack:wrinkle-release']);assert(!current.profile.generatorExtras.includes('Camera'));
  await p.evaluate(()=>{var profile=generatorPrefs(),groups=profile.prefItems.map(g=>({title:g.title,items:g.items.map(x=>({label:x.label,on:x.on}))}));localStorage.setItem(packingDraftPath('preferences'),JSON.stringify({version:1,context:JSON.stringify(profile)+'|older-form-fields',data:{fields:{'gp-custom':{value:profile.generatorExtras.concat(['Emergency pouch']).join('\n')}},custom:{groups:groups,removed:profile.prefRemoved || []}}}));generatorPreferences();});assert(await p.getByLabel('Always bring Emergency pouch',{exact:true}).isChecked(),'old preference draft not migrated');assert(!await p.evaluate(()=>generatorPrefs().generatorExtras.includes('Emergency pouch')),'old draft silently applied');await button('Save my preferences').click();await p.waitForSelector('.sheet-bg',{state:'detached'});assert(await p.evaluate(()=>generatorPrefs().generatorExtras.includes('Emergency pouch')));assert.equal(await p.evaluate(()=>refineEvaluate(refineLoad(TRIPS.MENUS),generatorPrefs(),[]).items.find(x=>x.label==='Lens cleaner').section),'Liquid toiletries');
  assert.deepEqual(errors,[]);console.log('OK: activity-first setup, collapsed optional drafts, central decision cards, travel/outfits/preferences, selective questions, date Undo, protected legacy items, section-aware always-bring items, old drafts and mobile layout');
}catch(e){console.error(e.stack || e.message);process.exitCode=1;}finally{await browser.close();server.close();}
