import assert from "node:assert/strict";
import vm from "node:vm";
import {readFileSync} from "node:fs";
const saved=new Map();
const c=vm.createContext({document:{getElementById(){return null;},addEventListener(){}},window:{addEventListener(){}},localStorage:{getItem(k){return saved.get(k)||null;}},console,setTimeout,clearTimeout});
for(const name of ["shared/core.js","packing-list/preferences.js","packing-list/packing.js","packing-list/generator.js","packing-list/refinement-engine.js","packing-list/refinement-state.js"]){vm.runInContext(readFileSync(new URL('../'+name,import.meta.url),'utf8'),c);}
const trip={id:"TEST",name:"Test",where:"Phoenix",start:"2026-10-08",end:"2026-10-14"};
assert.equal(c.refineDays('2026-10-31','2026-11-02'),3);assert.throws(()=>c.refineDays('2026-02-30','2026-03-02'),/valid calendar/);assert.throws(()=>c.refineDays('2026-10-01','2026-12-01'),/1–60/);
const profile=JSON.parse(JSON.stringify(c.PACK_PREFS));
let state=c.refineNewState(trip,{});
function run(changed=null,p=profile){const r=c.refineEvaluate(state,p,changed);state.ruleResults=r.ruleResults;state.ruleKeys=r.ruleKeys;state.profileSignature=r.profileSignature;return r;}
function item(result,id){return result.items.find(x=>x.id===id);}
let r=run();assert.equal(item(r,'pack:socks').quantity,13);assert.equal(item(r,'wear:socks').quantity,1);assert.equal(item(r,'pack:tshirts').quantity,6);assert.equal(item(r,'pack:contacts').quantity,10);assert(r.warnings.some(x=>x.id==='weather'));
state.refinements.laundry={available:true,firstWash:2,interval:2};r=run(['laundry']);assert.equal(item(r,'pack:socks').quantity,5);assert.equal(item(r,'pack:tshirts').quantity,2);assert.equal(item(r,'pack:contacts').quantity,10);assert.deepEqual(Array.from(r.ran),['clothing','activities']);
state.refinements.laundry={available:true,firstWash:2,interval:30};r=run([]);assert.equal(item(r,'pack:socks').quantity,11);assert.deepEqual(Array.from(r.ran),['clothing','activities']);
state.refinements.laundry={available:true,firstWash:6,interval:2};r=run(['laundry']);assert.equal(item(r,'pack:socks').quantity,13);
state.refinements.packingMode='light';r=run(['packingMode']);assert(!item(r,'pack:kindle'));assert.equal(state.refinements.packingMode,'standard');assert(item(r,'pack:whoop-charger'));assert(item(r,'pack:contacts'));assert.equal(item(r,'pack:socks').quantity,13);
state.refinements.rain=true;state.refinements.climate='hot';r=run(['rain','climate']);assert(item(r,'pack:rain-jacket'));assert(!item(r,'pack:light-packable-puffer-jacket'));assert(!item(r,'pack:lulu-joggers'));
state.inputs.activities.hike=true;r=run(['activities']);assert(!item(r,'pack:hiking-footwear'));assert(item(r,'wear:brooks-running-shoes').required);state.refinements.ruggedHike=true;r=run([]);assert(item(r,'pack:hiking-footwear'));assert(!item(r,'pack:daypack'));state.refinements.daypack=true;r=run([]);assert(item(r,'pack:daypack'));assert.equal(r.items.filter(x=>x.id==='pack:daypack').length,1);assert(item(r,'pack:daypack').required);
state.overrides.removed['pack:rain-jacket']=true;r=run([]);assert(!item(r,'pack:rain-jacket'));assert(r.warnings.some(x=>x.id==='hiking-rain'));
state.overrides.edited['pack:socks']={...item(r,'pack:socks'),quantity:8};state.refinements.packingMode='extra';r=run(['packingMode']);assert.equal(item(r,'pack:socks').quantity,8);assert(item(r,'pack:socks').manual);assert(item(r,'pack:socks').reasons.some(x=>x.includes('extra clothing day')));
delete state.overrides.edited['pack:socks'];r=run([]);assert.equal(item(r,'pack:socks').quantity,15);
state.overrides.added['manual:test']={id:'manual:test',label:'Camera',quantity:2,section:'Gear'};r=run([]);assert.equal(item(r,'manual:test').quantity,2);
state.refinements.work='work';r=run([]);assert.deepEqual(Array.from(r.ran),['work']);assert(item(r,'pack:work-computer-charger'));assert(r.warnings.some(x=>x.id==='work-baggage'));
state.overrides.removed['pack:work-computer']=true;r=run([]);assert(r.warnings.some(x=>x.id==='removed:pack:work-computer'));assert(!r.groups.at(-1).items.some(x=>x.label==='Work computer packed?'));
state.overrides.edited['pack:contacts']={...item(r,'pack:contacts'),quantity:5};r=run([]);assert(r.warnings.some(x=>x.id==='quantity:pack:contacts'));
state.refinements.climate='cold';state.refinements.thermal='hot';r=run(['climate','thermal']);assert(item(r,'pack:gloves'));assert(item(r,'pack:light-packable-puffer-jacket'));
const excluded=c.refineExclude(profile,{id:'pack:kindle',label:'Kindle'});state.refinements.packingMode='standard';r=run(['packingMode'],excluded);assert(!item(r,'pack:kindle'));
excluded.refinementProfile.excluded['pack:contacts']='Contacts';r=run(['profile'],excluded);assert(item(r,'pack:contacts'));assert(r.warnings.some(x=>x.id==='excluded:pack:contacts'));
assert.equal(r.groups.at(-1).title,'Before leaving');
r=run([],excluded);assert.deepEqual(Array.from(r.ran),[]);
state.overrides.edited['pack:light-packable-puffer-jacket']={...item(r,'pack:light-packable-puffer-jacket'),section:'Clothing'};r=run([],excluded);assert.equal(item(r,'pack:light-packable-puffer-jacket').section,'Clothing');
state.inputs.bag='checked';r=run([],excluded);assert.deepEqual(Array.from(r.ran),[]);
state.refinements.formalDays=1;r=run([],excluded);assert.deepEqual(Array.from(r.ran),['events']);
const snapshot=c.refineSnapshot({...state,undo:{something:true},undoProfile:{something:true}});assert(!snapshot.undo);assert(!snapshot.undoProfile);
saved.set('ta:trip/OLD/pack_meta/draft',JSON.stringify({groups:[{title:'Clothing',items:['Socks ×3','Special shirt ×2']},{title:'Before leaving',depart:true,items:['Grab wallet']}]}));
c.generatorSaved=()=>({groups:[]});const legacy=c.refineLoad({...trip,id:'OLD'});assert(legacy.legacy);let old=c.refineLegacyResult(legacy);assert.equal(item(old,'pack:socks').quantity,3);assert.equal(old.items.length,2);
legacy.legacy=false;old=c.refineEvaluate(legacy,profile,null);assert.equal(item(old,'pack:socks').quantity,3);assert.equal(old.items.filter(x=>x.id==='pack:socks').length,1);assert(item(old,'pack:special-shirt'));
// Confirm Tyler's selected preferences and interactions across conditions.
state=c.refineNewState(trip,{workout:true,climate:'cool'});r=run();
assert.equal(item(r,'pack:tshirts').quantity,6);assert.equal(item(r,'pack:lulu-shorts').quantity,4);
assert(item(r,'pack:light-packable-puffer-jacket'));assert(item(r,'wear:sweatshirt-hoodie'));assert.equal(item(r,'pack:light-packable-puffer-jacket').section,'Clothing');
state.refinements.thermal='hot';r=run([]);assert(item(r,'pack:light-packable-puffer-jacket'));assert(item(r,'pack:lulu-joggers'));
state.inputs.bag='checked';const checked=run([]);state.inputs.bag='carryon';r=run([]);
assert.deepEqual(r.items.map(x=>[x.id,x.quantity,x.section]),checked.items.map(x=>[x.id,x.quantity,x.section]));
state.overrides.edited['pack:lulu-shorts']={...item(r,'pack:lulu-shorts'),quantity:1};r=run([]);assert.equal(item(r,'pack:lulu-shorts').quantity,1);assert(r.warnings.some(x=>x.id==='quantity:pack:lulu-shorts'));
state.refinements.laundry={available:true,firstWash:2,interval:2};r=run([]);assert.equal(item(r,'pack:tshirts').quantity,2);assert.equal(item(r,'pack:lulu-shorts').quantity,1);assert(r.warnings.some(x=>x.id==='quantity:pack:lulu-shorts'));assert.equal(item(r,'pack:contacts').quantity,10);
delete state.overrides.edited['pack:lulu-shorts'];r=run([]);assert.equal(item(r,'pack:lulu-shorts').quantity,2);
state.overrides.removed['pack:lulu-shorts']=true;r=run([]);assert(!item(r,'pack:lulu-shorts'));assert(r.warnings.some(x=>x.id==='removed:pack:lulu-shorts'));delete state.overrides.removed['pack:lulu-shorts'];
state.refinements.packingMode='extra';r=run([]);assert.equal(item(r,'pack:tshirts').quantity,3);assert.equal(item(r,'pack:lulu-shorts').quantity,3);assert.equal(item(r,'pack:lulu-joggers').quantity,1);assert.equal(item(r,'pack:socks').quantity,7);assert(!item(r,'pack:kindle'));
state.inputs.activities.fish=true;r=run([]);const fishing=r;assert(item(r,'pack:fishing-gear'));state.inputs.activities.fish=false;r=run([]);assert(!item(r,'pack:fishing-gear'));assert(c.refineChanges(fishing,r).some(x=>x==='Removed Fishing gear'));
state.inputs.activities.hike=true;state.refinements.ruggedHike=false;r=run([]);assert(!item(r,'pack:hiking-footwear'));state.refinements.rain=true;r=run([]);assert(!item(r,'pack:hiking-footwear'));state.refinements.ruggedHike=true;r=run([]);assert(item(r,'pack:hiking-footwear'));
state.inputs.activities.hike=false;r=run([]);assert(!item(r,'pack:hiking-footwear'));assert(item(r,'pack:water-bottle').required);
const excludeShorts=c.refineExclude(profile,{id:'pack:lulu-shorts',label:'Lulu shorts'});r=run([],excludeShorts);assert(item(r,'pack:lulu-shorts'));assert(r.warnings.some(x=>x.id==='excluded:pack:lulu-shorts'));
const oldState=c.refineNewState(trip,{});oldState.inputs.activities={run:true,hike:false,water:false,fish:false};oldState.refinements.packingMode='light';oldState.overrides.edited['pack:socks']={id:'pack:socks',label:'Socks',quantity:8,section:'Clothing'};oldState.ruleResults={clothing:[{id:'stale'}]};oldState.ruleKeys={clothing:'old-cache'};saved.set('ta:'+c.refinePath('MIGRATE'),JSON.stringify(oldState));const migrated=c.refineLoad({...trip,id:'MIGRATE'});assert(migrated.inputs.activities.workout);assert(!('run' in migrated.inputs.activities));assert.equal(migrated.refinements.packingMode,'standard');const newResult=c.refineEvaluate(migrated,profile,[]);assert.equal(item(newResult,'pack:socks').quantity,8);assert.equal(item(newResult,'pack:tshirts').quantity,6);assert(!item(newResult,'pack:kindle'));assert(!item(newResult,'stale'));
state=c.refineNewState(trip,{hike:true});r=run();assert(!item(r,'pack:daypack'));state.refinements.daypack=true;r=run([]);assert.deepEqual(Array.from(r.ran),['activities']);assert.equal(item(r,'pack:daypack').quantity,1);state.refinements.daypack=false;r=run([]);assert(!item(r,'pack:daypack'));
state.refinements.daypack=true;r=run([]);state.overrides.edited['pack:daypack']={...item(r,'pack:daypack'),quantity:2};state.refinements.daypack=false;r=run([]);assert.equal(item(r,'pack:daypack').quantity,2);assert(item(r,'pack:daypack').manual);
// Optional electronics are not usual defaults; selecting Garmin includes its charger.
state=c.refineNewState(trip,{});r=run();
for(const id of ['kindle','hotspot','belkin-charging-pad','garmin','garmin-charger','extra-phone-case'])assert(!item(r,'pack:'+id));
for(const id of ['snacks','water-bottle','anker-battery-pack','whoop-charger','dryer-washing-sheets','wrinkle-release','airpods','glasses','costa-sunglasses','eye-drops','ibuprofen','zyrtec','prep-h','toothbrush','nail-clippers','tweezers','dirty-clothes-bag'])assert(item(r,'pack:'+id),id);
assert.equal(item(r,'pack:usb-c-cord').quantity,2);assert.equal(item(r,'pack:usb-c-hub').quantity,2);
state.refinements.extraItems={kindle:true,hotspot:true,chargingPad:true,garmin:true,phoneCase:true};r=run([]);assert.deepEqual(Array.from(r.ran),['extras']);
for(const id of ['kindle','hotspot','belkin-charging-pad','garmin','garmin-charger','extra-phone-case'])assert(item(r,'pack:'+id));assert.equal(r.items.filter(x=>x.id==='pack:garmin-charger').length,1);
state.overrides.edited['pack:kindle']={...item(r,'pack:kindle'),quantity:2};state.refinements.extraItems={};r=run([]);assert.equal(item(r,'pack:kindle').quantity,2);assert(!item(r,'pack:garmin'));assert(!item(r,'pack:garmin-charger'));assert(item(r,'pack:snacks'));
console.log('OK: selective rules, interactions, override persistence, critical protection, defaults, legacy migration, and export dependencies');
