import assert from "node:assert/strict";
import vm from "node:vm";
import {readFileSync} from "node:fs";
const saved=new Map();
const c=vm.createContext({document:{getElementById(){return null;},addEventListener(){}},window:{addEventListener(){}},localStorage:{getItem(k){return saved.get(k)||null;}},console,setTimeout,clearTimeout});
for(const name of ["shared/core.js","packing-list/preferences.js","packing-list/packing.js","packing-list/generator.js","packing-list/refinement-engine.js","packing-list/refinement-state.js"]){vm.runInContext(readFileSync(new URL('../'+name,import.meta.url),'utf8'),c);}
const trip={id:"TEST",name:"Test",where:"Phoenix",start:"2026-10-08",end:"2026-10-14"};
assert.equal(c.refineDays('2026-10-31','2026-11-02'),3);assert.throws(()=>c.refineDays('2026-02-30','2026-03-02'),/valid calendar/);assert.throws(()=>c.refineDays('2026-10-01','2026-12-01'),/1–60/);
const profile=JSON.parse(JSON.stringify(c.PACK_PREFS));
let state=c.refineNewState(trip,{});
function run(changed=null,p=profile){const r=c.refineEvaluate(state,p,changed);state.ruleResults=r.ruleResults;state.ruleKeys=r.ruleKeys;state.profileSignature=r.profileSignature;return r;}
function item(result,id){return result.items.find(x=>x.id===id);}
let r=run();assert.equal(item(r,'pack:socks').quantity,13);assert.equal(item(r,'wear:socks').quantity,1);assert.equal(item(r,'pack:tshirts').quantity,6);assert.equal(item(r,'pack:contacts').quantity,10);assert(r.warnings.some(x=>x.id==='weather'));
state.refinements.laundry={available:true,firstWash:2,interval:2};r=run(['laundry']);assert.equal(item(r,'pack:socks').quantity,5);assert.equal(item(r,'pack:tshirts').quantity,2);assert.equal(item(r,'pack:contacts').quantity,10);assert.deepEqual(Array.from(r.ran),['clothing','activities']);
state.refinements.laundry={available:true,firstWash:2,interval:30};r=run([]);assert.equal(item(r,'pack:socks').quantity,11);assert.deepEqual(Array.from(r.ran),['clothing','activities']);
state.refinements.laundry={available:true,firstWash:6,interval:2};r=run(['laundry']);assert.equal(item(r,'pack:socks').quantity,13);
state.refinements.packingMode='light';r=run(['packingMode']);assert(!item(r,'pack:kindle'));assert.equal(state.refinements.packingMode,'standard');assert(item(r,'pack:whoop-charger'));assert(item(r,'pack:contacts'));assert.equal(item(r,'pack:socks').quantity,13);
state.refinements.rain=true;state.refinements.climate='hot';r=run(['rain','climate']);assert(item(r,'pack:rain-jacket'));assert(!item(r,'pack:light-packable-puffer-jacket'));assert(!item(r,'pack:lulu-joggers'));
state.inputs.activities.hike=true;r=run(['activities']);assert(!item(r,'pack:hiking-footwear'));assert(item(r,'wear:brooks-running-shoes').required);state.refinements.ruggedHike=true;r=run([]);assert(item(r,'pack:hiking-footwear'));assert(!item(r,'pack:daypack'));state.refinements.daypack=true;r=run([]);assert(item(r,'pack:daypack'));assert.equal(r.items.filter(x=>x.id==='pack:daypack').length,1);assert(item(r,'pack:daypack').required);
state.overrides.removed['pack:rain-jacket']=true;r=run([]);assert(!item(r,'pack:rain-jacket'));assert(r.warnings.some(x=>x.id==='hiking-rain'));
state.overrides.edited['pack:socks']={...item(r,'pack:socks'),quantity:8};state.refinements.packingMode='extra';r=run(['packingMode']);assert.equal(item(r,'pack:socks').quantity,8);assert(item(r,'pack:socks').manual);assert(item(r,'pack:socks').reasons.some(x=>x.includes('Laundry coverage')));
delete state.overrides.edited['pack:socks'];r=run([]);assert.equal(item(r,'pack:socks').quantity,13);
state.overrides.added['manual:test']={id:'manual:test',label:'Camera',quantity:2,section:'Gear'};r=run([]);assert.equal(item(r,'manual:test').quantity,2);
state.refinements.work='work';r=run([]);assert.deepEqual(Array.from(r.ran),['events','work']);assert(item(r,'pack:work-computer-charger'));assert(r.warnings.some(x=>x.id==='work-baggage'));
state.overrides.removed['pack:work-computer']=true;r=run([]);assert(r.warnings.some(x=>x.id==='removed:pack:work-computer'));assert(!r.groups.at(-1).items.some(x=>x.label==='Work computer packed?'));
state.overrides.edited['pack:contacts']={...item(r,'pack:contacts'),quantity:5};r=run([]);assert(r.warnings.some(x=>x.id==='quantity:pack:contacts'));
state.refinements.climate='cold';state.refinements.thermal='hot';r=run(['climate','thermal']);assert(item(r,'pack:gloves'));assert(item(r,'pack:light-packable-puffer-jacket'));
const excluded=c.refineExclude(profile,{id:'pack:kindle',label:'Kindle'});state.refinements.packingMode='standard';r=run(['packingMode'],excluded);assert(!item(r,'pack:kindle'));
excluded.refinementProfile.excluded['pack:contacts']='Contacts';r=run(['profile'],excluded);assert(item(r,'pack:contacts'));assert(r.warnings.some(x=>x.id==='excluded:pack:contacts'));
assert.equal(r.groups.at(-1).title,'Before leaving');
r=run([],excluded);assert.deepEqual(Array.from(r.ran),[]);
state.overrides.edited['pack:light-packable-puffer-jacket']={...item(r,'pack:light-packable-puffer-jacket'),section:'Clothing'};r=run([],excluded);assert.equal(item(r,'pack:light-packable-puffer-jacket').section,'Clothing');
state.inputs.bag='checked';r=run([],excluded);assert.deepEqual(Array.from(r.ran),[]);
state.refinements.formalDays=1;r=run([],excluded);assert.deepEqual(Array.from(r.ran),['events']);
const snapshot=c.refineSnapshot({...state,undo:{something:true},undoProfile:{something:true}});assert(!snapshot.undo);assert(!snapshot.undoProfile);
saved.set('ta:trip/OLD/pack_meta/draft',JSON.stringify({groups:[{title:'Clothing',items:['Socks ×3','Special shirt ×2']},{title:'Before leaving',depart:true,items:['Grab wallet']}]}));
c.generatorSaved=()=>({groups:[]});const legacy=c.refineLoad({...trip,id:'OLD'});assert(legacy.legacy);let old=c.refineLegacyResult(legacy);assert.equal(item(old,'pack:socks').quantity,3);assert.equal(old.items.length,2);
legacy.legacy=false;old=c.refineEvaluate(legacy,profile,null);assert.equal(item(old,'pack:socks').quantity,3);assert.equal(old.items.filter(x=>x.id==='pack:socks').length,1);assert(item(old,'pack:special-shirt'));
// Confirm Tyler's selected preferences and interactions across conditions.
state=c.refineNewState(trip,{workout:true,climate:'cool'});r=run();
assert.equal(item(r,'pack:tshirts').quantity,6);assert.equal(item(r,'pack:lulu-shorts').quantity,4);
assert(item(r,'pack:light-packable-puffer-jacket'));assert(item(r,'wear:sweatshirt-hoodie'));assert.equal(item(r,'pack:light-packable-puffer-jacket').section,'Clothing');
state.refinements.thermal='hot';r=run([]);assert(item(r,'pack:light-packable-puffer-jacket'));assert(item(r,'pack:lulu-joggers'));
state.inputs.bag='checked';const checked=run([]);state.inputs.bag='carryon';r=run([]);
assert.deepEqual(r.items.map(x=>[x.id,x.quantity,x.section]),checked.items.map(x=>[x.id,x.quantity,x.section]));
state.overrides.edited['pack:lulu-shorts']={...item(r,'pack:lulu-shorts'),quantity:1};r=run([]);assert.equal(item(r,'pack:lulu-shorts').quantity,1);assert(r.warnings.some(x=>x.id==='quantity:pack:lulu-shorts'));
state.refinements.laundry={available:true,firstWash:2,interval:2};r=run([]);assert.equal(item(r,'pack:tshirts').quantity,2);assert.equal(item(r,'pack:lulu-shorts').quantity,1);assert(r.warnings.some(x=>x.id==='quantity:pack:lulu-shorts'));assert.equal(item(r,'pack:contacts').quantity,10);
delete state.overrides.edited['pack:lulu-shorts'];r=run([]);assert.equal(item(r,'pack:lulu-shorts').quantity,2);
state.overrides.removed['pack:lulu-shorts']=true;r=run([]);assert(!item(r,'pack:lulu-shorts'));assert(r.warnings.some(x=>x.id==='removed:pack:lulu-shorts'));delete state.overrides.removed['pack:lulu-shorts'];
state.refinements.packingMode='extra';r=run([]);assert.equal(item(r,'pack:tshirts').quantity,2);assert.equal(item(r,'pack:lulu-shorts').quantity,2);assert.equal(item(r,'pack:lulu-joggers').quantity,1);assert.equal(item(r,'pack:socks').quantity,5);assert(!item(r,'pack:kindle'));
state.inputs.activities.fish=true;r=run([]);const fishing=r;assert(item(r,'pack:fishing-gear'));state.inputs.activities.fish=false;r=run([]);assert(!item(r,'pack:fishing-gear'));assert(c.refineChanges(fishing,r).some(x=>x==='Removed Fishing gear'));
state.inputs.activities.hike=true;state.refinements.ruggedHike=false;r=run([]);assert(!item(r,'pack:hiking-footwear'));state.refinements.rain=true;r=run([]);assert(!item(r,'pack:hiking-footwear'));state.refinements.ruggedHike=true;r=run([]);assert(item(r,'pack:hiking-footwear'));
state.inputs.activities.hike=false;r=run([]);assert(!item(r,'pack:hiking-footwear'));assert(item(r,'pack:water-bottle').required);
const excludeShorts=c.refineExclude(profile,{id:'pack:lulu-shorts',label:'Lulu shorts'});r=run([],excludeShorts);assert(item(r,'pack:lulu-shorts'));assert(r.warnings.some(x=>x.id==='excluded:pack:lulu-shorts'));
const oldState=c.refineNewState(trip,{});oldState.inputs.activities={run:true,hike:false,water:false,fish:false};oldState.refinements.packingMode='light';oldState.overrides.edited['pack:socks']={id:'pack:socks',label:'Socks',quantity:8,section:'Clothing'};oldState.ruleResults={clothing:[{id:'stale'}]};oldState.ruleKeys={clothing:'old-cache'};saved.set('ta:'+c.refinePath('MIGRATE'),JSON.stringify(oldState));const migrated=c.refineLoad({...trip,id:'MIGRATE'});assert(migrated.inputs.activities.workout);assert(!('run' in migrated.inputs.activities));assert.equal(migrated.refinements.packingMode,'standard');const newResult=c.refineEvaluate(migrated,profile,[]);assert.equal(item(newResult,'pack:socks').quantity,8);assert.equal(item(newResult,'pack:tshirts').quantity,6);assert(!item(newResult,'pack:kindle'));assert(!item(newResult,'stale'));
state=c.refineNewState(trip,{hike:true});r=run();assert(!item(r,'pack:daypack'));state.refinements.daypack=true;r=run([]);assert.deepEqual(Array.from(r.ran),['activities']);assert.equal(item(r,'pack:daypack').quantity,1);state.refinements.daypack=false;r=run([]);assert(!item(r,'pack:daypack'));
state.refinements.daypack=true;r=run([]);state.overrides.edited['pack:daypack']={...item(r,'pack:daypack'),quantity:2};state.refinements.daypack=false;r=run([]);assert.equal(item(r,'pack:daypack').quantity,2);assert(item(r,'pack:daypack').manual);
// Optional electronics are not usual defaults; selecting Garmin includes its charger.
state=c.refineNewState(trip,{});r=run();
for(const id of ['kindle','hotspot','belkin-charging-pad','garmin','garmin-charger','extra-phone-case'])assert(!item(r,'pack:'+id));
for(const id of ['snacks','water-bottle','anker-battery-pack','whoop-charger','dryer-washing-sheets','wrinkle-release','airpods','glasses','costa-sunglasses','eye-drops','ibuprofen','zyrtec','prep-h','toothbrush','nail-clippers','tweezers','dirty-clothes-bag'])assert(item(r,'pack:'+id),id);
assert.equal(item(r,'pack:usb-c-cord').quantity,2);assert.equal(item(r,'pack:usb-c-hub').quantity,2);
state.refinements.extraItems={kindle:true,hotspot:true,chargingPad:true,garmin:true,phoneCase:true};r=run([]);assert.deepEqual(Array.from(r.ran),['extras']);
for(const id of ['kindle','hotspot','belkin-charging-pad','garmin','garmin-charger','extra-phone-case'])assert(item(r,'pack:'+id));assert.equal(r.items.filter(x=>x.id==='pack:garmin-charger').length,1);
state.overrides.edited['pack:kindle']={...item(r,'pack:kindle'),quantity:2};state.refinements.extraItems={};r=run([]);assert.equal(item(r,'pack:kindle').quantity,2);assert(!item(r,'pack:garmin'));assert(!item(r,'pack:garmin-charger'));assert(item(r,'pack:snacks'));
// Dressed occasions share compatible items, not blindly summed independent lists.
state=c.refineNewState(trip,{});state.refinements.work='laptop';state.refinements.workDays=6;state.refinements.dinners=3;state.refinements.dinnerTop='buttonup';state.refinements.dinnerBottoms='khakis';state.refinements.formalDays=2;r=run();
assert.equal(item(r,'pack:button-up-long-sleeve-shirt').quantity,6);assert.equal(item(r,'pack:white-shirt').quantity,2);assert(item(r,'pack:suit-jacket'));assert(item(r,'pack:dress-pants'));assert.equal(item(r,'pack:dress-socks').quantity,2);assert(!r.items.some(x=>/undershirt|extra-tie/.test(x.id)));assert.equal(item(r,'pack:tie').quantity,2);assert.equal(r.items.filter(x=>x.id==='pack:belt').length,1);
state.refinements.laundry={available:true,firstWash:2,interval:2};const beforeNice=r;r=run([]);assert.equal(item(r,'pack:button-up-long-sleeve-shirt').quantity,6);assert.equal(item(r,'pack:white-shirt').quantity,2);assert.equal(item(r,'pack:tshirts').quantity,2);assert(!r.ran.includes('events'));
state.refinements.tie=true;state.refinements.alternateKhakis=true;r=run([]);assert(item(r,'pack:tie'));assert.equal(r.items.filter(x=>x.id==='pack:khakis').length,1);assert.equal(item(r,'pack:khakis').quantity,2);
state.refinements.shirtOverlap=1;r=run([]);assert.equal(item(r,'pack:button-up-long-sleeve-shirt').quantity,8);
state.refinements.shareSuitShirts=true;r=run([]);assert(!item(r,'pack:button-up-long-sleeve-shirt'));assert.equal(item(r,'pack:white-shirt').quantity,8);state.refinements.suitOverlap=0;r=run([]);assert.equal(item(r,'pack:white-shirt').quantity,10);
state.refinements.formalDays=0;r=run([]);assert.equal(item(r,'pack:button-up-long-sleeve-shirt').quantity,8);assert(!item(r,'pack:white-shirt'));assert(!item(r,'pack:suit-jacket'));
state.refinements.dinnerTop='polo';r=run([]);assert.equal(item(r,'pack:button-up-long-sleeve-shirt').quantity,6);assert.equal(item(r,'pack:polo-shirts').quantity,3);
state.refinements.dinnerBottoms='shorts';r=run([]);assert.equal(r.items.filter(x=>x.id==='pack:lulu-shorts').length,1);assert(!item(r,'pack:khakis'));
state.refinements.climate='cold';state.refinements.warmWeather=true;r=run([]);assert(item(r,'pack:gloves'));assert(item(r,'pack:lulu-shorts'));
// Dinner alternatives remain separate from work shirts and recalculate only affected rules.
state=c.refineNewState(trip,{work:'laptop',workDays:3,dinners:2});state.refinements.dinnerTop='shortsleeve';state.refinements.dinnerBottoms='other';state.refinements.dinnerOtherBottoms='Dress shorts';r=run();assert.equal(item(r,'pack:short-sleeve-nice-shirts').quantity,2);assert.equal(item(r,'pack:button-up-long-sleeve-shirt').quantity,3);assert.equal(item(r,'pack:dinner-other-bottoms').quantity,1);assert.equal(item(r,'pack:belt').quantity,1);assert.equal(c.refineWardrobe(state).overlapMax,0);
state.refinements.dinnerTop='longsleeve';r=run([]);assert.deepEqual(Array.from(r.ran),['events']);assert.equal(item(r,'pack:long-sleeve-nice-shirts').quantity,2);assert(!item(r,'pack:short-sleeve-nice-shirts'));
state.refinements.dinnerTop='other';state.refinements.dinnerOtherTop='Linen dinner shirt';state.refinements.dinnerOtherBelt=false;state.refinements.laundry={available:true,firstWash:1,interval:1};r=run([]);assert.equal(item(r,'pack:dinner-other-top').quantity,2);assert.equal(item(r,'pack:dinner-other-top').label,'Linen dinner shirt');assert(!item(r,'pack:belt'));
state.decisionReviews['Dinner outfit']=c.refineDecisionKey(state,'Dinner outfit');state.refinements.dinnerOtherTop='Silk dinner shirt';assert(c.refinePendingDecisions(state).includes('Dinner outfit'));r=run([]);assert.deepEqual(Array.from(r.ran),['events']);assert.equal(item(r,'pack:dinner-other-top').label,'Silk dinner shirt');
state.overrides.edited['pack:dinner-other-top']={...item(r,'pack:dinner-other-top'),quantity:5};state.refinements.dinnerOtherTop='Another top';r=run([]);assert.equal(item(r,'pack:dinner-other-top').quantity,5);state.refinements.formalDays=1;r=run([]);assert.equal(item(r,'pack:belt').quantity,1,'Suit belt remains required even when other dinner bottoms do not need it');
state.refinements.dinnerOtherTop=' ';state.decisionReviews['Dinner outfit']=c.refineDecisionKey(state,'Dinner outfit');assert(c.refinePendingDecisions(state).includes('Dinner outfit'),'Blank custom names cannot bypass export confirmation');
// Toiletries follow physical bags, retain quantities/identity, and share one departure check.
state=c.refineNewState(trip,{});r=run();assert.equal(item(r,'pack:toothbrush').section,'Dry toiletries');assert.equal(item(r,'pack:toothpaste').section,'Liquid toiletries');assert.equal(item(r,'pack:contacts').section,'Dry toiletries');assert.equal(item(r,'pack:contacts').quantity,10);assert(!r.items.some(x=>/liquids.*bag/i.test(x.label)));let checks=r.groups.find(g=>g.depart).items.map(c.refineLabel);assert.equal(checks.filter(x=>x==='Toiletries packed?').length,1);assert(!checks.some(x=>/Liquids bag/i.test(x)));
state.overrides.edited['pack:toothpaste']={...item(r,'pack:toothpaste'),section:'Dry toiletries'};r=run([]);assert.equal(item(r,'pack:toothpaste').section,'Dry toiletries','Explicit bag choice survives recalculation');
state.ruleResults.consumables.push(c.refineItem('Liquids quart bag (travel-size)','Toiletries','Old automatic rule',{required:true}));for(const key of Object.keys(state.ruleKeys))state.ruleKeys[key]=state.ruleKeys[key].replace('wardrobe-2026-10-v3:','wardrobe-2026-10-v2:');r=run([]);assert(!r.items.some(x=>/liquids.*bag/i.test(x.label)),'Old cached bag survives updated rules');
// Professional rotation is capped; explicit opt-outs and edits survive.
state=c.refineNewState(trip,{formal:1});r=run();assert.equal(item(r,'pack:tie').quantity,1);assert.equal(item(r,'pack:khakis').quantity,1);assert.equal(item(r,'pack:white-shirt').label,'White dress shirts');
state.refinements.formalDays=5;r=run([]);assert.equal(item(r,'pack:tie').quantity,2);assert.equal(item(r,'pack:khakis').quantity,2);assert.equal(item(r,'pack:white-shirt').quantity,5);
state.overrides.edited['pack:tie']={...item(r,'pack:tie'),quantity:3};state.refinements.tie=false;state.refinements.alternateKhakis=false;c.refineNormalizeState(state);r=run([]);assert.equal(state.refinements.tie,false);assert.equal(item(r,'pack:tie').quantity,3);assert(!item(r,'pack:khakis'));
// Confirmation changes with context; old boolean "reviewed" flags cannot bypass required decisions.
state=c.refineNewState(trip,{work:'laptop',formal:2,dinners:2});state.reviewed={Work:true,Events:true};assert(c.refinePendingDecisions(state).includes('Work'));assert(c.refinePendingDecisions(state).includes('Dinner outfit'));assert(c.refinePendingDecisions(state).includes('Suit outfit'));
state.refinements.workDays=3;state.refinements.dinnerTop='buttonup';state.refinements.dinnerBottoms='jeans';for(const step of ['Work','Dinner outfit','Suit outfit','Shirt sharing'])state.decisionReviews[step]=c.refineDecisionKey(state,step);assert.equal(c.refinePendingDecisions(state).length,0);
state.refinements.dinners=3;assert(c.refinePendingDecisions(state).includes('Dinner outfit'));assert(c.refinePendingDecisions(state).includes('Shirt sharing'));state.refinements.dinners=0;state.refinements.formalDays=0;assert.equal(c.refinePendingDecisions(state).length,0);
// A spare set is kept when a late laundry plan has not already supplied a buffer.
state=c.refineNewState(trip,{});state.refinements.packingMode='extra';r=run();assert.equal(item(r,'pack:socks').quantity,15);assert.equal(item(r,'pack:tshirts').quantity,7);
state.refinements.laundry={available:true,firstWash:7,interval:7};r=run([]);assert.equal(item(r,'pack:socks').quantity,15);
const imported=c.refineNewState(trip,{work:'laptop'});for(const key of ['workDays','dinnerTop','dinnerBottoms','tie','alternateKhakis','shareSuitShirts','shirtOverlap','suitOverlap','warmWeather'])delete imported.refinements[key];delete imported.decisionReviews;imported.reviewed={Work:true};c.refineNormalizeState(imported);assert.equal(imported.refinements.workDays,null);assert(c.refinePendingDecisions(imported).includes('Work'));
state=c.refineNewState(trip,{});state.inputs.tripType='event';state.reviewed.Events=true;assert(c.refinePendingDecisions(state).includes('Events'));state.decisionReviews.Events=c.refineDecisionKey(state,'Events');assert(!c.refinePendingDecisions(state).includes('Events'));state.inputs.end='2026-10-15';assert(c.refinePendingDecisions(state).includes('Events'));
// Dinner needs one suitable pair, not every pair recommended by casual-clothing rules.
state=c.refineNewState(trip,{});state.refinements.dinners=2;state.refinements.dinnerTop='polo';state.refinements.dinnerBottoms='shorts';r=run();state.overrides.edited['pack:lulu-shorts']={...item(r,'pack:lulu-shorts'),quantity:1};r=run([]);assert(!r.warnings.some(x=>x.id==='quantity:pack:lulu-shorts'));state.inputs.activities.workout=true;r=run([]);assert(r.warnings.some(x=>x.id==='quantity:pack:lulu-shorts'));
// Long trips without laundry: Laundry is a required, fingerprinted decision; quantities stay literal until answered.
{const long=c.refineNewState({...trip,start:'2026-10-08',end:'2026-10-16'},{});assert.equal(c.refineDays(long.inputs.start,long.inputs.end),9);assert.deepEqual(Array.from(c.refinePendingDecisions(long)),['Laundry']);const lr=c.refineEvaluate(long,profile,null);assert.equal(lr.items.find(x=>x.id==='pack:tshirts').quantity,8,'no wash assumed before Laundry is answered');
long.decisionReviews.Laundry=c.refineDecisionKey(long,'Laundry');assert.equal(c.refinePendingDecisions(long).length,0,'confirmed no laundry sticks');assert.equal(c.refineEvaluate(long,profile,null).items.find(x=>x.id==='pack:tshirts').quantity,8);
const moved=JSON.parse(JSON.stringify(long));moved.inputs.start='2026-11-08';moved.inputs.end='2026-11-16';assert.equal(c.refinePendingDecisions(moved).length,0,'same trip length keeps the confirmation');
moved.inputs.end='2026-11-17';assert.deepEqual(Array.from(c.refinePendingDecisions(moved)),['Laundry'],'trip length change reopens Laundry');
const washed=JSON.parse(JSON.stringify(long));washed.refinements.laundry.available=true;assert.equal(c.refinePendingDecisions(washed).length,0,'planned laundry needs no confirmation');washed.refinements.laundry.available=false;washed.refinements.laundry.interval=3;assert.deepEqual(Array.from(c.refinePendingDecisions(washed)),['Laundry'],'laundry input change reopens Laundry');
const eight=c.refineNewState({...trip,start:'2026-10-08',end:'2026-10-15'},{});assert.deepEqual(Array.from(c.refinePendingDecisions(eight)),['Laundry'],'8 days counts as long');
const short=c.refineNewState({...trip,start:'2026-10-08',end:'2026-10-13'},{});assert.equal(c.refinePendingDecisions(short).length,0,'6-day trip is not blocked');const seven=c.refineNewState({...trip,start:'2026-10-08',end:'2026-10-14'},{});assert.equal(c.refinePendingDecisions(seven).length,0,'7-day trip is not blocked');
const legacy=c.refineNewState({...trip,start:'2026-10-08',end:'2026-10-20'},{});legacy.legacy=true;assert.equal(c.refinePendingDecisions(legacy).length,0);}
// Built-in trip styles (Tyler, Oct 2026): five in order; styles never carry dates, destination, weather, counts or overrides.
{vm.runInContext(readFileSync(new URL('../packing-list/trip-styles.js',import.meta.url),'utf8'),c);
const styles=c.PACK_TRIP_STYLES,byId=Object.fromEntries(styles.map(x=>[x.id,x]));
assert.deepEqual(JSON.parse(JSON.stringify(styles.map(x=>[x.id,x.name]))),[['weekend','Weekend'],['wedding-weekend','Wedding / event weekend'],['beach-hawaii','Beach / Hawaii'],['hiking','Hiking (cooler)'],['international','International']]);
assert.deepEqual(Array.from(c.packingTripStyles(),x=>x.id),Array.from(styles,x=>x.id),'no saved custom styles in this context');
for(const s of styles){assert.deepEqual({...s.refinements.laundry},{available:false,firstWash:4,interval:4},s.id);assert.equal(s.refinements.packingMode,'standard',s.id);assert.equal(s.refinements.work,'none',s.id);for(const k of ['where','start','end'])assert(!(k in s.inputs),s.id+' carries '+k);for(const k of ['climate','rain','formalDays','dinners','workDays','dinnerTop','dinnerBottoms','warmWeather'])assert(!(k in s.refinements),s.id+' carries '+k);assert(!('overrides' in s),s.id);}
assert.deepEqual([byId.weekend.inputs.tripType,byId.weekend.inputs.bag,byId.weekend.inputs.mode],['leisure','carryon','drive']);
const wed=byId['wedding-weekend'].inputs;assert.deepEqual([wed.tripType,wed.bag,wed.mode,wed.occasions],['event','carryon','fly',true]);
const beach=byId['beach-hawaii'];assert.deepEqual([beach.inputs.bag,beach.inputs.mode],['carryon','fly']);assert.deepEqual({...beach.inputs.activities},{water:true,hike:true,workout:true});assert(!beach.refinements.ruggedHike);
const hiking=byId.hiking;assert.deepEqual([hiking.inputs.bag,hiking.inputs.mode],['carryon','fly']);assert.deepEqual({...hiking.inputs.activities},{hike:true});assert.equal(hiking.refinements.ruggedHike,true);assert.equal(hiking.refinements.daypack,true);assert(!hiking.refinements.brooksToo);
const intl=byId.international.inputs;assert.deepEqual([intl.tripType,intl.bag,intl.mode,intl.intl],['leisure','carryon','fly',true]);
// Beach / Hawaii: swimming + ordinary hiking + workouts; Brooks once, sandals with swimming, no hiking footwear.
state=c.refineNewState(trip,{});Object.assign(state.inputs,JSON.parse(JSON.stringify(beach.inputs)));Object.assign(state.refinements,JSON.parse(JSON.stringify(beach.refinements)));r=run();
assert(item(r,'pack:swimsuit'));assert(item(r,'pack:sandals'));assert.equal(item(r,'pack:sandals').section,'Clothing');assert(!item(r,'pack:sandals').required,'sandals stay excludable');assert(!item(r,'pack:hiking-footwear'));assert.equal(r.items.filter(x=>x.id==='wear:brooks-running-shoes').length,1);assert(item(r,'pack:lulu-shorts'));
const noSandals=JSON.parse(JSON.stringify(profile));noSandals.maybe.find(g=>g.tag==='water').items=['Swimsuit'];r=run([],noSandals);assert(item(r,'pack:sandals'),'older saved profiles still get sandals for swimming');assert.equal(r.items.filter(x=>x.id==='pack:sandals').length,1);
const excl=JSON.parse(JSON.stringify(profile));excl.refinementProfile={excluded:{'pack:sandals':true}};r=run([],excl);assert(!item(r,'pack:sandals'),'sandals can be excluded');assert(!r.warnings.some(x=>x.itemId==='pack:sandals'));
state.inputs.activities.water=false;r=run([]);assert(!item(r,'pack:sandals'),'sandals follow swimming');
// Hiking (cooler): rugged trails swap Brooks for hiking footwear; Also bring Brooks packs both and reruns activities only.
state=c.refineNewState(trip,{});Object.assign(state.inputs,JSON.parse(JSON.stringify(hiking.inputs)));Object.assign(state.refinements,JSON.parse(JSON.stringify(hiking.refinements)));c.refineNormalizeState(state);assert.equal(state.refinements.brooksToo,false);r=run();
assert(item(r,'pack:hiking-footwear'));assert(item(r,'pack:daypack'));assert(!item(r,'wear:brooks-running-shoes').required,'rugged hikes do not require Brooks by themselves');assert(!r.warnings.some(x=>x.id==='activity-shoes'));
const noBrooks=JSON.parse(JSON.stringify(profile));noBrooks.refinementProfile={excluded:{'wear:brooks-running-shoes':true}};r=run([],noBrooks);assert(!item(r,'wear:brooks-running-shoes'),'profile exclusion removes usual Brooks on rugged hikes');state.refinements.brooksToo=true;r=run([],noBrooks);assert(item(r,'wear:brooks-running-shoes').required,'Also bring Brooks overrides the exclusion as a required item');assert(item(r,'pack:hiking-footwear'));state.refinements.brooksToo=false;r=run();
state.refinements.brooksToo=true;r=run([]);assert.deepEqual(Array.from(r.ran),['activities']);assert(item(r,'pack:hiking-footwear'));assert(item(r,'wear:brooks-running-shoes').required);assert.equal(r.items.filter(x=>x.id==='wear:brooks-running-shoes').length,1);
state.inputs.activities.workout=true;r=run([]);assert.equal(r.items.filter(x=>x.id==='wear:brooks-running-shoes').length,1,'workouts and Also bring Brooks share one pair');state.inputs.activities.workout=false;
state.overrides.removed['wear:brooks-running-shoes']=true;r=run([]);assert(r.warnings.some(x=>x.id==='activity-shoes'),'missing Brooks warned when Also bring Brooks is on');delete state.overrides.removed['wear:brooks-running-shoes'];
state.refinements.brooksToo=false;r=run([]);assert.deepEqual(Array.from(r.ran),['activities']);assert(!item(r,'wear:brooks-running-shoes').required);assert(item(r,'pack:hiking-footwear'));
state.refinements.brooksToo=true;state.refinements.ruggedHike=false;r=run([]);assert(!item(r,'pack:hiking-footwear'));assert.equal(r.items.filter(x=>x.id==='wear:brooks-running-shoes').length,1);
state.inputs.activities.hike=false;r=run([]);assert(!item(r,'wear:brooks-running-shoes').required,'Also bring Brooks applies only to hikes');
const old=c.refineNewState(trip,{});delete old.refinements.brooksToo;c.refineNormalizeState(old);assert.equal(old.refinements.brooksToo,false,'older states normalize Also bring Brooks off');}
// Bluetooth speaker and Floppy hat are opt-in trip extras, off by default even for Beach / Hawaii.
{state=c.refineNewState(trip,{water:true,hike:true,workout:true});r=run();assert(!item(r,'pack:bluetooth-speaker'));assert(!item(r,'pack:floppy-hat'));assert.equal(c.refineOptionalKey('Bluetooth speaker'),'speaker');assert.equal(c.refineOptionalKey('Floppy hat'),'floppyHat');
state.refinements.extraItems={speaker:true,floppyHat:true};r=run([]);assert.deepEqual(Array.from(r.ran),['extras']);assert.equal(item(r,'pack:bluetooth-speaker').section,'Personal bag & day gear');assert.equal(item(r,'pack:floppy-hat').section,'Clothing');assert(item(r,'wear:hat'),'usual hat stays');
state.refinements.extraItems={};r=run([]);assert(!item(r,'pack:bluetooth-speaker'));assert(!item(r,'pack:floppy-hat'));
const usual=JSON.parse(JSON.stringify(profile));usual.extras[0].items.push('Floppy hat');usual.extras[2].items.push('Bluetooth speaker');r=run([],usual);assert(!item(r,'pack:floppy-hat') && !item(r,'pack:bluetooth-speaker') && !item(r,'wear:floppy-hat'),'opt-in extras never become usual defaults');}
console.log('OK: selective rules, interactions, override persistence, critical protection, defaults, legacy migration, and export dependencies');
