// Focused regression checks for reusable test scenarios and refinement review.
import http from 'node:http';import {readFile} from 'node:fs/promises';import {join,dirname,extname} from 'node:path';import {fileURLToPath} from 'node:url';
let pw;try{pw=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');}catch{console.log('SKIP: playwright not installed');process.exit(0);}
const root=join(dirname(fileURLToPath(import.meta.url)),'..'),server=http.createServer(async(req,res)=>{let path=req.url.split('?')[0];if(path.endsWith('/'))path+='index.html';try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'})[extname(path)] || 'application/octet-stream');res.end(await readFile(join(root,path)));}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=process.env.PACKING_BASE_URL || `http://127.0.0.1:${server.address().port}/packing-list/`,browser=await pw.chromium.launch({executablePath:process.env.CHROMIUM_PATH || undefined}),p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
function assert(value,message){if(!value)throw new Error(message);}
try{
  await p.goto(base+'?test=1');await p.click('button:has-text("Choose a test scenario")');await p.fill('#pt-days','4');await p.fill('#pt-workDays','0');await p.fill('#pt-formal','10');await p.click('button:has-text("Save setup configuration")');assert(await p.evaluate(()=>packingTestLibrary().length)===0,'invalid suit count was saved');assert((await p.textContent('#pt-error')).includes('whole number'),'invalid count not explained');assert(await p.inputValue('#pt-formal')==='10','count was silently changed');
  await p.fill('#pt-days','0');await p.click('button:has-text("Reset & generate list")');assert(!await p.evaluate(()=>!!TRIPS['PACKING-TEST']),'invalid trip duration started');
  await p.selectOption('#pt-scenario','laundry');await p.click('button:has-text("Reset & generate list")');await p.waitForSelector('#rr-export');
  await p.click('button[aria-label="Laundry"]');await p.fill('#rf-first','2');await p.fill('#rf-interval','2');await p.click('button:has-text("Apply & recalculate")');await p.waitForSelector('.sheet-bg',{state:'detached'});
  await p.click('button[aria-label="Packing"]');await p.selectOption('#rf-packing','extra');await p.click('button:has-text("Apply & recalculate")');await p.waitForSelector('.sheet-bg',{state:'detached'});
  await p.locator('[data-item-id="pack:tshirts"]').getByRole('button',{name:'Edit',exact:true}).click();await p.fill('#ri-quantity','9');await p.click('button:has-text("Save override")');await p.waitForSelector('.sheet-bg',{state:'detached'});
  await p.click('button:has-text("Test menu / reset")');await p.fill('#pt-name','Two-day laundry with manual shirts');await p.click('button:has-text("Save current test as variant")');assert(await p.inputValue('#pt-firstWash')==='2','capture did not refresh editor');await p.click('button:has-text("Reset & generate list")');await p.waitForSelector('#rr-export');
  let saved=await p.evaluate(()=>refineLoad(TRIPS['PACKING-TEST']));assert(saved.refinements.laundry.firstWash===2 && saved.refinements.laundry.interval===2 && saved.refinements.packingMode==='extra','refined assumptions lost on immediate restart');assert(saved.overrides.edited['pack:tshirts'].quantity===9,'manual edit lost on restart');
  await p.click('button:has-text("Validate current test")');await p.waitForSelector('[data-current-check]');assert(await p.locator('[data-current-check="FAIL"]').count()===0,'valid refined variant failed');assert((await p.locator('[data-current-check="OVERRIDE"]').allTextContents()).some(x=>x.includes('T-shirts') && x.includes('actual 9')),'manual override hidden in validation');await p.click('button:has-text("Close")');
  await p.evaluate(()=>{var state=refineLoad(TRIPS['PACKING-TEST']);Object.values(state.ruleResults).flat().find(x=>x.id==='pack:contacts').quantity=1;lsSet('ta:'+refinePath('PACKING-TEST'),state);});await p.click('button:has-text("Validate current test")');assert((await p.locator('[data-current-check="FAIL"]').allTextContents()).some(x=>x.includes('Contacts')),'stale non-clothing cache passed validation');await p.click('button:has-text("Close")');
  await p.click('button:has-text("Test menu / reset")');await p.uncheck('#pt-includeManual');await p.fill('#pt-name','Assumptions only');await p.click('button:has-text("Save current test as variant")');await p.click('button:has-text("Reset & generate list")');await p.waitForSelector('#rr-export');saved=await p.evaluate(()=>refineLoad(TRIPS['PACKING-TEST']));assert(Object.keys(saved.overrides.edited).length===0 && saved.refinements.laundry.firstWash===2,'manual edit option did not preserve assumptions only');
  assert(await p.locator('.refine-one').count()===0 && await p.locator('#rr-adjust').count()===1,'duplicate assumption controls remain');assert(await p.getByRole('button',{name:'Outfits & work',exact:true}).count()===1,'central trip plan lost work choices');
  await p.getByRole('button',{name:'Outfits & work',exact:true}).click();await p.getByRole('button',{name:'Days & work equipment',exact:true}).click();await p.selectOption('#rf-work','work');await p.fill('#rf-workDays','3');await p.click('button:has-text("Apply & recalculate")');await p.waitForSelector('.sheet-bg',{state:'detached'});
  await p.click('button:has-text("Test menu / reset")');await p.fill('#pt-name','Full work gear');await p.click('button:has-text("Save current test as variant")');await p.click('button:has-text("Reset & generate list")');await p.waitForSelector('#rr-export');assert(await p.evaluate(()=>refineLoad(TRIPS['PACKING-TEST']).refinements.work)==='work','full work setup was converted to laptop only');
  await p.click('button:has-text("Test menu / reset")');await p.click('button:has-text("Save as another scenario")');const labels=await p.evaluate(()=>packingTestLibrary().map(x=>x.label));assert(new Set(labels).size===labels.length,'duplicate names indistinguishable');await p.click('button:has-text("Close")');await p.click('button:has-text("Test menu / reset")');assert((await p.locator('#pt-scenario option:checked').textContent()).includes('Copy'),'last saved selection was lost');
  for(const width of [360,390,430]){for(const colorScheme of ['light','dark']){await p.setViewportSize({width,height:844});await p.emulateMedia({colorScheme});await p.evaluate(()=>document.querySelector('.test-sheet .sheet-body').scrollTop=10000);assert(await p.locator('.test-actions').isVisible(),'launch actions disappeared');assert(await p.locator('.test-preview').isVisible(),'preview disappeared');assert(await p.locator('.test-preview').evaluate(x=>x.clientHeight)>80,'preview collapsed');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile overflow');}}
  assert(errors.length===0,errors.join('; '));console.log('OK: invalid input, refined variants, manual edits, fresh validation, relevant reviews, saved selection and mobile controls');
}catch(e){console.error(e.stack || e.message);process.exitCode=1;}finally{await browser.close();server.close();}
